### ISSUE TITLE
SingleView titles are positioned too high on the screen when no image is present

### ISSUE THREAD

**Issue by kevin-birdy** [ApollosProject/apollos-prototype#1003]
### Details
Especially on iPhone X, the title is bumping against the safe area when no image is present.

### Expected Behavior
In the case that no image is present, the title should receive extra paddings so that it is not pressing up against the very top of the screen. 

### Actual Behavior
The text is pressed to the very top of my iPhoneXR screen. It is difficult to see via screenshot, but the black texts literally touches the black edge of my device screen.
![IMG_1DE0CD2283C6-1](https://user-images.githubusercontent.com/41083408/63186927-e084e800-c01a-11e9-9e0b-dbe8f4d2c525.jpeg)

### Possible Fix
I typically never let anything go closer than 80px from the top of the screen so that it always looks good even with the iPhone X ears.

<details><summary>Additional Info</summary>

### Your Environment
Current Testflight build (538) on iPhone XR

### Steps to Reproduce

1.  Open the app
2. Scroll down the home feed until you get to the "10 ways to refresh your spirit every day" article
3. Badabingbadabooya

</details>

**Comment by vinnyjth** [comment]
I believe we fixed this at some point
