### ISSUE TITLE
The spacing in the `MiniPlayer` is too close

### ISSUE THREAD

**Issue by kevin-birdy** [ApollosProject/apollos-prototype#1011]
### Apollos Version: x.x.x
1.1.0

### Details
The play and close icons are really close in the current `MiniPlayer`. Additionally, the title could use a bit of breathing room as well.

### Expected Behavior

- Title is 16px from the image
- 24px around the icons (check my screenshot)

### Actual Behavior
Looks like 8px tops between the icons and the text is 8px from the image

![Media Player](https://user-images.githubusercontent.com/41083408/63192231-d6b5b180-c027-11e9-9ffa-0f92c06dd0dc.png)

### Another note
I don't know where to put this but I want to bring it to your attention... see how much smaller the 'X' is in the bottom version vs. the top version. I am quite willing to bet that those are both 12px icons because the play buttons look the same. The reason there is a difference is that the original icons baked unnecessary padding into the .svg itself 🙄I would like to provide a new close icon that removes this padding ideally... probably another conversation though.

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by redreceipt** [comment]
@kevin-birdy what do you think about this? It's not exactly 24px around the icons, the title is flexed 2:1 to the icons and they are flexed with `space-evenly`. 24px around the icons was making the title very small.

<img width="463" alt="Screen Shot 2019-09-03 at 8 30 43 AM" src="https://user-images.githubusercontent.com/2659478/64173542-88752080-ce25-11e9-8650-debc2ff7d106.png">

**Comment by kevin-birdy** [comment]
I think this is way better. I have big thumbs :) So it was a pretty small tappable area before. I'm not too concerned with truncating more of the title. Chances are the users remember what they are listening to and in the off case they blacked out and forgot it's only a tap away 👍

**Comment by redreceipt** [comment]
we're still getting user feedback that it is still difficult to close

**Comment by kevin-birdy** [comment]
@redreceipt can you elaborate on "difficult to close"? As in the tappable area is still too small? They aren't identifying the icon? Something else?

**Comment by redreceipt** [comment]
yea tappable too small is the feedback we're getting

**Comment by kevin-birdy** [comment]
Sorry I've now created a filter in my gmail. These all go to my updates folder and I miss them.

I'm playing around with the media player in Sketch right now and I think the biggest reason the icons feel so small is that I'm pretty sure the Core icons have padding baked into them whereas my Sketch ones do not. So...I think the best way forward is to simply increase the size of the icons from 12px to 16px and maintain all of the same spacing logic.

I _think_ that should make a significant difference. At that point we can consider moving up in size again if necessary. Personally, I am not concerned with having to truncate a bit more of the title. There will already be plenty of context available for the user and if for some reason they want to see all of a really long title they can just tap to expand full screen.

**Comment by redreceipt** [comment]
PR is up

--
Michael Neeley
Junior Web Developer
NewSpring Church
www.newspring.cc
Cell: (803) 622-6599
