### ISSUE TITLE
MiniPlayer is pushing against the safe area at the bottom of the screen

### ISSUE THREAD

**Issue by kevin-birdy** [ApollosProject/apollos-prototype#1012]
### Apollos Version: x.x.x
1.1.0 (538)

### Details
The media player is still really low on the screen

### Expected Behavior
There should be ample space between the home indicator and the `MiniPlayer`

### Actual Behavior
The `MiniPlayer` is basically touching the home indicator
![IMG_023221656666-1](https://user-images.githubusercontent.com/41083408/63192553-9276e100-c028-11e9-866f-1f4c5900957c.jpeg)

### Possible Fix
Make sure the `MiniPlayer` never goes inside of the safe zone (34px)
<img width="275" alt="Screen Shot 2019-08-16 at 1 18 54 PM" src="https://user-images.githubusercontent.com/41083408/63192521-8559f200-c028-11e9-8aab-4c704f29821f.png">

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by vinnyjth** [comment]
Done in #1043
