### ISSUE TITLE
Make it so that the native header back arrow/text is tied to the theme

### ISSUE THREAD

**Issue by kevin-birdy** [ApollosProject/apollos-prototype#1013]
### User Story
As a user, I want to experience a consistent branding throughout the app

### Description
My suggestion is to not use the iOS blue (and the Android equivalent) and instead make the native navigation tied to theme colors.

### Why
This way the app is still consistent with the church's brand and native navigation, but it doesn't look like we slapped an out-of-the-box iOS header at the top of the screen.

### Other Resources
In Testflight, this could be tied to our `secondary` color 👇
![IMG_61BFD09B91A2-1](https://user-images.githubusercontent.com/41083408/63192859-4bd5b680-c029-11e9-8976-1d4997946339.jpeg)

**Comment by redreceipt** [comment]
@kevin-birdy I can't reproduce, where is this screen?

**Comment by redreceipt** [comment]
I got it now, on Android, it's black and looks better, was throwing me off. I understand we want both to use the primary theme color, not the defaults.

**Comment by kevin-birdy** [comment]
Ya, I still have it using the iOS blue in build 538 as well. It's when ever you drill into a category view. It's the same for profile settings, as well as Recently Liked.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/41083408/64187166-c1b58c80-ce35-11e9-9565-11a173ec9363.gif)

**Comment by vinnyjth** [comment]
Done in #1043
