### ISSUE TITLE
Get Sermon Week Number

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#1022]
### User Story

As a developer, I want to know what week in a series the current sermon is so I can do things with it

### Description

I'd like the server to return a new field called `seriesIndex` or something so I can know what week number a sermon is in the series. 

### Why

- It will allow us to gray out the current sermon in the horizontal scroll bar
- it will allow us to show "Week Number X of Y" on the content item

### Acceptance Criteria

* [ ] It should expose a new field on the `WeekendContentItem` node called `seriesIndex`

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by redreceipt** [comment]
@vinnyjth what do think about the suggestion above? `siblingContentConnection.currentIndex` and `sibilingContentConnection.totalItems`

**Comment by vinnyjth** [comment]
> @vinnyjth don't we already do something like this in core?
Yep! That is working fine in core. 

`sibilingContentConnection.totalItems` is done in Relay, so we're off to a good start there :) In that context, I think I would be okay doing a `currentIndex`.

However, `sibilingContentConnection` is just a `ContentItemsConnection`, which makes this more difficult. I'm still struggling to understand why, if you're going to add a "currentIndex" there, why not do that on the client? I can understand it being necessary to have that data on the server if you ever want to load just the middle of a list and have the correct index, but we don't do that anywhere in the app yet.

**Comment by redreceipt** [comment]
Only for the chance that we may want to know its index outside of the context of a list. We could use the same list of IDs from the `totalCount` algorithm and `index` would just be null if it wasn't in there, as would be the case for `childContentConnection`.

**Comment by redreceipt** [comment]
> `sibilingContentConnection.totalItems` is done in Relay, so we're off to a good start there :)

Not sure what Relay is but isn't this already done with our `totalCount` field?

**Comment by vinnyjth** [comment]
It is :) I would encourage you to try and implement what you need on the front end without a schema index first, and if you run into a situation where it's impossible to get the data you need, and you know that the "sort" index from the API would help you out, we can add that field to the API.
