### ISSUE TITLE
Lock Cocoapods Version

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#1041]
### User Story

As a developer, I want to make sure I have the right version of `cocoapods` installed so there are no conflicts when I build iOS.

### Description

Need to lock down the version of `cocoapods` used among devs. We can do this via a `Gemfile` and `bundler`.

This will add a `yarn pods` script that will:

```
bundle install
bundle exec pod install --repo-update
```

... which can be added onto the end of `yarn nuke`

### Why

Currently, if the version is off (website vs. Homebrew for example) it won't build unless you run `pod install` first and then discard the changes to the `Podfile.lock` after you're done. Could become a headache.

### Acceptance Criteria

* [ ] It should add a `yarn pods` command

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by redreceipt** [comment]
Just a placeholder in case this becomes a headache.

<img width="754" alt="Screen Shot 2019-09-03 at 2 14 59 PM" src="https://user-images.githubusercontent.com/2659478/64198736-d48c8900-ce56-11e9-9f11-c3793214a2ce.png">

**Comment by vinnyjth** [comment]
I forgot about this comment 😂 Thanks @redreceipt !

**Comment by vinnyjth** [comment]
(We ended up going the bundler route)
