### ISSUE TITLE
Incorrect Tabbar size on initial screen load

### ISSUE THREAD

**Issue by cdanwards** [ApollosProject/apollos-prototype#1071]
### Details

On the initial app load, and on the initial load of any piece of content, the tabbar is incorrectly sized. It presents as the larger 'landscape' tabbar. If you navigate away then navigate back the tabbar is correct.

### Expected Behavior

Tab Bar should only occupy space for icons on initial load.

### Actual Behavior

The Tab Bar is applying the landscape styles on initial load.

### Possible Fix

🤷‍♂ 

![Initial_TabBar](https://user-images.githubusercontent.com/8878532/65839412-35cf3d00-e2db-11e9-8690-f3017f303e39.gif)

**Comment by vinnyjth** [comment]
Fixed in #1095
