### ISSUE TITLE
Location Finder Distance Wrong

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#1076]
### Details

The distance to the campus on the location finder screen always says "0mi". I propose it just shouldn't have distance here, if it's there campus, they don't care at this point how far it is. That information is only useful on the mapview.

<img width="463" alt="Screen Shot 2019-09-30 at 3 21 44 PM" src="https://user-images.githubusercontent.com/2659478/65909303-501a2100-e396-11e9-91c8-345c32336307.png">

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by vinnyjth** [comment]
Nice catch.

**Comment by vinnyjth** [comment]
Fixed in #1078
