### ISSUE TITLE
Summary broken in content series content item

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#1083]
### Details

When using the `Summary` field in Rock, it doesn't seem to pull in the summary for a `ContentSeriesContentItem`

<img width="1440" alt="Screen Shot 2019-10-01 at 1 43 26 PM" src="https://user-images.githubusercontent.com/2659478/65986515-ff67fe00-e451-11e9-8d7e-0e7f5c7c81ff.png">

<img width="1440" alt="Screen Shot 2019-10-01 at 1 43 22 PM" src="https://user-images.githubusercontent.com/2659478/65986522-01ca5800-e452-11e9-8390-d638e91c9a81.png">

### Expected Behavior

`summary` field should show summary

### Actual Behavior

`summary` field is blank

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by vinnyjth** [comment]
Fixed in #1084
