### ISSUE TITLE
Allow sorting the content channels in the Discover Feed

### ISSUE THREAD

**Issue by richarddubay** [ApollosProject/apollos-prototype#1091]
### User Story
As a church I'd like to be able to select the order in which the content channels display in the Discover feed. This is beneficial because then people could get to the most used (or most important) content quicker.

### Description
This feature allows us to set the order on the content channels in the Discover feed.

### Why
Flexibility. Each church may have a different idea of what is important and this would allow them to get their most important content in front of their users quicker.

### Acceptance Criteria
* [ ] It should allow for custom ordering of the content channels in the Discover feed.

### Possible Implementation & Open Questions
I think the most simple solution would just be to honor the order of the `DISCOVER_CONTENT_CHANNEL_IDS` in the `config.yml`. But definitely open to better solutions.

**Comment by vinnyjth** [comment]
We solve this in Willow like this: https://github.com/Differential/willow-prototype/commit/6b0c67ab701410a52aa7ce3f2a66771c4b88120b#diff-6839320655a9c043f1cfb3311b062e9c

Not exactly great - I would love to rely on some sort order set in rock - but works well enough.

**Comment by vinnyjth** [comment]
@erikkgagewhitt This is a good API issue to solve! I think your best option is to do something like I did in Willow (^), but maybe move the sorting method to the `dataSource` :)

**Comment by richarddubay** [comment]
FWIW, @redreceipt ended up doing something pretty much exactly like this in our code.

**Comment by erikkgagewhitt** [comment]
@vinnyjth I'm curious as to why this change is necessary. I changed the order of the ids without making any changes to the rest of the code; that seemed to change the order of the channels on the discover tab.

**Comment by vinnyjth** [comment]
@erikkgagewhitt I believe it works under certain circumstances right now, but it's not consistent because it relies on Rock always returning items in the same order (and it doesn't always do that :)
