### ISSUE TITLE
Key/Value Features Aren't Safely Decoded

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#1096]
### Details

`TextFeature` field in Rock is assuming it's text to be shown (I guess) so it's decoded safely through the API. `Features` which is a key/value pair array is not.

![Screenshot_20191006-142010](https://user-images.githubusercontent.com/2659478/66273803-59e3ce80-e845-11e9-97c9-2cd177bdedac.png)

### Expected Behavior

text features should be decoded.

### Actual Behavior

they aren't

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by vinnyjth** [comment]
Fixed in #1097
