### ISSUE TITLE
Add Tests for Query Components

### ISSUE THREAD

**Issue by richarddubay** [ApollosProject/apollos-prototype#110]
## User Story

As a developer, I want to make sure that our app is tested as well as possible so that I can be confident that what we send to our people works.

In this case, add tests to the `<Query>` components that we’ve created this far. See https://dev-blog.apollodata.com/testing-apollos-query-component-d575dc642e04 and https://www.apollographql.com/docs/guides/testing-react-components.html.

#### Acceptance Criteria _(Optional)_

* [ ] It should test our current `<Query>` components.

**Comment by conrad-vanl** [comment]
Here's an example with such a test in our repo:
https://github.com/ApollosProject/apollos-prototype/pull/124/commits/1922687973063fdeb9e0898d4f3b9fe261c9d690#diff-098b0d5eccde949ef4cdf1d85b0dc5ff
