### ISSUE TITLE
Reduce "YellowScreen" warnings. 

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-prototype#1108]
### Apollos Version: x.x.x

We get an "enjoyable" amount of YellowScreen warnings when booting the app. Some of them we can ignore, and some of them we can (and should) fix. 

![image](https://user-images.githubusercontent.com/1637694/66410359-fa5dfe00-e9bf-11e9-864c-65a11b73e3fc.png)

### Details

From the image above, the warnings I would focus on knocking out are (in order of "bang for buck")

- `OneSignal the configure method has been deprecated`
- `componentWillMount is deprecated` You might have to update Storybook to fix this
- `AsyncStorage has been extracted from react-native core` one of our packages we rely on is using this. 
- `propType title marked as required / propType coverImage marked as required`

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by erikkgagewhitt** [comment]
One of the `componentWillReceiveProps` warnings is in the Query component; the only way to fix that would be to upgrade react-apollo to 3.0.0, but it seems to be full of breaking changes, so I'm not sure that would work.

**Comment by erikkgagewhitt** [comment]
Yup, definitely breaks everything.

**Comment by vinnyjth** [comment]
@erikkgagewhitt Feel free to skip that one :)

**Comment by erikkgagewhitt** [comment]
@vinnyjth Some of these prop warnings seem to come from not having loading components; is that something I should add?

**Comment by vinnyjth** [comment]
@erikkgagewhitt Can you clarify / give an example? The answer is "maybe, but might need to be done in a separate PR"

**Comment by erikkgagewhitt** [comment]
FeaturedCard is a pretty good example. When it first mounts inside of ContentCardConnected, `isLoading` is true. That means the FeaturedCard will render without the title prop. When `isLoading` becomes false, the component is then rendered, wrapped in a Query component which eventually returns title.

If there was a loading component, this would not be a problem; since there isn't, we get the prop warning.

**Comment by vinnyjth** [comment]
Ah! So I think the interesting thing in that case is that `FeaturedCard` has a loading component baked into it. It renders something different if `isLoading` is true. That puts us in this weird scenario where the `.requiredProps` are different, depending on if `isLoading` is `true` or `false`. My vote is to take a look at `FeaturedCard` and change the `propTypes` to reflect that. 

Here's a similar example of how to handle something like that
https://stackoverflow.com/questions/42299335/react-props-set-isrequired-on-a-prop-if-another-prop-is-null-empty

**Comment by erikkgagewhitt** [comment]
Okay, then I'll make the props conditionally required!

**Comment by erikkgagewhitt** [comment]
@vinnyjth Would it be better to convert the lifecycle components to UNSAFE or replace them as React Native advises?
