### ISSUE TITLE
getMembers Doesn't Resolve

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#1131]
### Details

Just tried to use [this](https://github.com/ApollosProject/apollos-prototype/blob/65f8dca4aae38ab62e93788e790ce4a6797b4614/packages/apollos-data-connector-rock/src/groups/data-source.js#L28) in another function call. 

```
const members = await Group.getMembers(1)
console.log(members)
```

shows...

```
Promise { <Pending> }
```

I think the return statement needs to be wrapped in a `Promise.all` or something???

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by vinnyjth** [comment]
Yah, wrapping that in `Promise.all` will fix that. You want to fix this for me?
