### ISSUE TITLE
iOS splash screen icon distorted

### ISSUE THREAD

**Issue by burkeshartsis** [ApollosProject/apollos-prototype#115]
## User Story

As an app user I don't want to see a distorted iOS splash screen so that I can feel like this is a solid product I can trust.

#### Problem Details

Not sure if it's iPhone X specific or not. Ignore the colors in the screen shot. The simulator loads so fast it was hard to get a screenshot of it before it faded away.

![Simulator Screen Shot - iPhone X - 2018-06-27 at 10.28.10.png](https://images.zenhubusercontent.com/58ee3ab351aa2c30577b2ae0/e5283e12-0f84-4294-a79e-933524ae428f)

**Comment by IsaacHardy** [comment]
Does this happen on a release build? Seems like it might only be an issue when developing the app.

**Comment by conrad-vanl** [comment]
I def see it on the release build :)

**Comment by cdanwards** [comment]
@burkeshartsis after looking through the files in xcode and all it looks like it's what you thought, with just the iPhone X being affected. Do we need more image files or is it a something we can change in that JSON file?
