### ISSUE TITLE
Can't Scroll Devotionals (Android)

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#1157]
### Details

On Android, you can't scroll through the devotionals because the tab view takes over.

![20191024_155130](https://user-images.githubusercontent.com/2659478/67520208-63a76780-f676-11e9-9f11-f97a1481e913.gif)

### Expected Behavior

touching the devotionals should scroll those, swiping anywhere else should swipe tabs

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by burkeshartsis** [comment]
Hey @redreceipt try as I might I'm not able to reproduce this in my simulator. 

![Oct-28-2019 13-21-29](https://user-images.githubusercontent.com/2053547/67701261-09641a80-f986-11e9-87e8-6978e72393f7.gif)

**Comment by redreceipt** [comment]
that gif above doesn't show the issue, you have to swipe on the tile cards at the bottom

**Comment by redreceipt** [comment]
sorry, I wasn't very clear on my description

**Comment by burkeshartsis** [comment]
Perfect. I'll take a look again. This helps a ton.

**Comment by erikkgagewhitt** [comment]
@burkeshartsis I think this is related to the pager changes as removing that change gets rid of this issue. :(
