### ISSUE TITLE
Media Player Over Locations

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#1160]
### Details

Minimized media player over top the locations button looks really bad

![original](https://user-images.githubusercontent.com/2659478/67523013-c9e2b900-f67b-11e9-9af7-81e023c5e340.jpg)

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by vinnyjth** [comment]
Closed in #1163
