### ISSUE TITLE
MapView Zooms In Too Far

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#1175]
### Details

When you open the `MapView` from the user settings page, the results are very inconsistent. Sometimes it zooms all the way in on just my location, sometimes it's all the way on just one campus, and sometimes it works as intended (showing my location and all campuses zoomed out)

![Screenshot_20191030-132550](https://user-images.githubusercontent.com/2659478/67882719-12d1bc00-fb19-11e9-81bd-3cf4140df9b5.png)

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by vinnyjth** [comment]
I believe we fixed this in #1189
