### ISSUE TITLE
HTML Renderer Handles Bold Text

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#1184]
### User Story

As a content writer, I should be able to use `<b>` tags to bold text.

### Description

Currently, the renderer can't handle `<b>` tags, only `<hX>` tags. The Rock editor only has a "Bold" button so unless you paste in the HTML, you can't bold the text without adding header tags in the code.

### Acceptance Criteria

* [ ] It should [SPEC_DETAIL]

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by vinnyjth** [comment]
Fixed in #1185
