### ISSUE TITLE
Search shouldn't show unapproved content

### ISSUE THREAD

**Issue by richarddubay** [ApollosProject/apollos-prototype#1197]
### Details
When performing a search, the results that come back are including content that is not approved in Rock. 

### Expected Behavior
When performing a search, only approved content should be displayed in the search results.

### Actual Behavior
When performing a search, unapproved content is displaying in the search results. For example, in the screenshots you will see that the news item "This October at NewSpring" is pending approval, but it displays in the search results.

<details><summary>Additional Info</summary>

### Steps to Reproduce
Run the app in your sim on `master`.
See that the "This October at NewSpring" item does not appear in the home feed.
Go to the discover tab and search for "NewSpring"
You will find the "This October at NewSpring" item appears in the search results.

Screenshots:
![Screenshot 2019-11-05 14 33 13](https://user-images.githubusercontent.com/3229463/68239877-ccc59e00-ffd9-11e9-92ad-39edd51f8bc8.png)
![Screenshot 2019-11-05 14 26 18](https://user-images.githubusercontent.com/3229463/68239888-d3541580-ffd9-11e9-8a91-5d500d1bccef.png)

</details>

**Comment by richarddubay** [comment]
@vinnyjth Just wanted to tag you so you could see this.

**Comment by vinnyjth** [comment]
Determined that this was a config issue :)
