### ISSUE TITLE
Content items with no children show 20 children

### ISSUE THREAD

**Issue by richarddubay** [ApollosProject/apollos-prototype#121]
#### Problem Details

Content that doesn't have any related children are pulling some default set of 20 children and displaying them in the horizontal scroller. Items that actually have children display them correctly (the correct items and the correct number of items). The attached screenshot is of a sermon that does not have any children according to the data in Rock, but as you can see it is pulling data and displaying it. Pulling the data for this via the API returns the data. I feel like this has something to do with `childContentItemsConnection`, but I'm not sure.

* Screenshots, GIFs, or a video
* Any additional information (version, device, etc.)

#### Acceptance Criteria _(Optional)_

* [ ] It should not pull any data for items that do not actually have any children.

**Comment by richarddubay** [comment]
<img width="545" alt="screenshot 2018-06-29 16 34 19" src="https://user-images.githubusercontent.com/3229463/42113899-04ce4224-7bbb-11e8-8c99-6c9af8239409.png">

**Comment by conrad-vanl** [comment]
Fixed in #89 #120
