### ISSUE TITLE
Pass a link handler to HTMLView

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-prototype#1224]
### User Story

As a user of HTMLView, I would like to pass an option function that would be called to open links in the app. 

Might be a good idea to feed a `openUrl` function to `defaultRenderer`

https://github.com/ApollosProject/apollos-prototype/blob/master/packages/apollos-ui-htmlview/src/HTMLView/defaultRenderer.js#L122

### Acceptance Criteria

* [ ] It should [SPEC_DETAIL]

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by erikkgagewhitt** [comment]
I want to make sure I understand this issue properly; we need an optional function that will, if passed, be called in place of `Linking.openUrl`. This function should open links in app as opposed to in the web, which is what - I assume - `Linking.openUrl does`

**Comment by vinnyjth** [comment]
You got it 100%! And this function would need to be passed as a prop to `HTMLView` https://github.com/ApollosProject/apollos-prototype/blob/master/packages/apollos-ui-htmlview/src/HTMLView/index.js#L12

**Comment by erikkgagewhitt** [comment]
@burkeshartsis Would like to know why we're doing this.

**Comment by erikkgagewhitt** [comment]
Actually, minor clarification:

Are we simply asking that this be opened in the in-app browser?

**Comment by conrad-vanl** [comment]
Lol, I'm confused by this one too. I remember some chatter coming across about a bug on the willow end.

Also - maybe it's to handle in-app links?

**Comment by vinnyjth** [comment]
I wanted to update Willow to use the in-app-browser package, and yah! This would be awesome for handling deep links.

I would hardcode this to use the IAB but then this package would have to rely on it.

**Comment by erikkgagewhitt** [comment]
Closed by https://github.com/ApollosProject/apollos-prototype/pull/1229
