### ISSUE TITLE
Improve campus picker in high latency situations

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-prototype#1231]
- Return an optimistic result when setting a campus
- make sure we don't wait for the mutation result before returning to the previous screen.

**Comment by erikkgagewhitt** [comment]
So, if we don't wait for the mutation to return, what happens if the mutation fails?

**Comment by vinnyjth** [comment]
@erikkgagewhitt The user would experience the campus switching back on them. Not the best case, but a failure is unlikely for this mutation.

**Comment by vinnyjth** [comment]
Another route you could explore that might be better in the failure state is showing a loading indicator on the "Select Campus" button. Would love @kevin-birdy's feedback here also.

**Comment by kevin-birdy** [comment]
In general, I think spinners inside primary buttons are always an effective way to convey to the user that something is happening, just be patient. Admittedly, "mutation" doesn't mean a whole lot to me so I am having a hard time visualizing the above problem. 

If someone wants to use some plain English synonyms I can probably add more value :)
