### ISSUE TITLE
Design pass on connect screen / next steps menu

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#133]
Open-ended design issue. Spend 16 story points working on improving the UX of the connect screen.

## User Story

As a `<type of user>` _(who)_ I want to `<perform an action>` _(what)_ so that I can `<achieve a goal>` _(why)_.

#### Problem Details _(Optional)_

* Screenshots, GIFs, or a video
* Any additional information (version, device, etc.)

#### Acceptance Criteria _(Optional)_

* [ ] It should [SPEC_DETAIL]

**Comment by burkeshartsis** [comment]
closing as duplicate of #227
