### ISSUE TITLE
FeaturedCard loading state broken with custom CardLabel

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#1332]
When using a custom card label with margin on a `FeaturedCard`, it draws a strange line at the bottom in the loading state. This image was generated in storybook

![Screen Shot 2020-02-05 at 3 40 52 PM](https://user-images.githubusercontent.com/2659478/73881208-ecb16b80-482d-11ea-84ba-1bf1f8c1b33c.png)
![Screen Shot 2020-02-05 at 3 37 33 PM](https://user-images.githubusercontent.com/2659478/73881216-efac5c00-482d-11ea-82a1-a7d7c9c25c31.png)

**Comment by redreceipt** [comment]
cc @burkeshartsis

**Comment by burkeshartsis** [comment]
while this is unfortunate, it is worth saying that attempting to reposition a label is likely outside the scope of that props support as there is just so many combinations of positional styles that could easily brake a particular layout. These cards are designed, built, and tested to be examples of what's possible and something you use with very minimal customization out of the box. They are not necessarily meant to support every permutation of what might be possible with the api they expose.

**Comment by redreceipt** [comment]
I could probably just do a `loading ? {} : margin` kinda thing I suppose, right?

**Comment by burkeshartsis** [comment]
so the crux of the issue is that you probably need to wrap the `CustomLabel` in a `View` and position that. The way the loading states work is that they render a difference component when loading but your positioning the component not the loading state.

**Comment by redreceipt** [comment]
gotcha, I'll try that. If it doesn't work, we can talk through options. Either way, I'll close this one.
