### ISSUE TITLE
Android Auth Next Button styles broken

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#1333]
Auth entry next button styles a little off

Code lives at `ui-auth/src/styles/NextButton`

![Screen Shot 2020-02-05 at 4 13 13 PM](https://user-images.githubusercontent.com/2659478/73883757-7ebb7300-4832-11ea-8a1d-7c95cd40fa11.png)

![Screen Shot 2020-02-05 at 4 10 31 PM](https://user-images.githubusercontent.com/2659478/73883570-2d12e880-4832-11ea-994f-f152bd3f7547.png)

**Comment by redreceipt** [comment]
cc @burkeshartsis

**Comment by burkeshartsis** [comment]
The fix for this is in #1305
