### ISSUE TITLE
Scope out audio player

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#140]
How should we integrate an audio player for Apollos?

Lets take our learnings from Ns/Apollos and scope out the "idea" solution for playing audio in Apollos Prototype.

Should support at an MVP level listening to sermon audio, but also potentially music listening. Should we try to do all of this in-app? Are there integrations with the native OS that we can use to provide a better music listening experience? Do we have data with how users listen to this type of audio on church apps today? Can we improve on that experience?

**Comment by burkeshartsis** [comment]
I am in full support of a going as native as possible with this. The [React Native Video package](https://github.com/react-native-community/react-native-video) supports an [audio only](https://github.com/react-native-community/react-native-video#audioonly) option. Using this library would address most desires and issues with media playback on a mobile device (native controls, ignore ios mute, access to playback analytics, airplay/hdmi/etc support, video <-> audio handoff, etc. etc. etc.)

**Comment by burkeshartsis** [comment]
From a learning perspective, I think there is a lot of opportunity to better organize, present, and leverage the massive amounts of media (audio and video) some organizations have/create. One thing I noticed related to this topic is how NewSpring sectioned off music, and co-located sermon video and audio. I believe there was also videos sprinkled into devotionals and articles but I'm not certain those relate to the topic at hand as much. I digress, one of the most powerful things Netflix and Youtube has taught us from a UX perspective is how we browse media content is not the same as written media. Furthermore, interfaces are not optimized for ease of navigation so much as discovery and consumption. HMW, create an engaging media experience for users that balances consumption with opportunities to take action on the things they are watching and listening too.
