### ISSUE TITLE
Hook up live stream API to live ChOP data

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#142]
## User Story

A user can watch the live stream during a church's live stream service time

#### Acceptance Criteria _(Optional)_

* [ ] Gets data from ChOP API
* [ ] Determine if there's a way we can mock this or artificially trigger live or not (cuz the apollos church won't really ever be "live"). Maybe we can upload a fake schedule to ChOP?

**Comment by richarddubay** [comment]
@conrad-vanl In addition to https://newspring.churchonline.org/api/v1/upcoming_event_times, I also found out about this end point: https://newspring.churchonline.org/api/v1/events/current

It seems to show the next event and whether or not it's live. This might be a good place to start?
