### ISSUE TITLE
Home feed / digital bulletin integration

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#161]
Investigate how we can land on the feature request surrounding turning the home feed into a "digital bulletin" of sorts. For MVP, I think this is largely just considering how the home feed is sorted, making sure we're putting the most relevant content at top, and possibly giving the church some control what items appear in the home feed.

**Comment by richarddubay** [comment]
@IsaacHardy @conrad-vanl @cdanwards I took a look at the home feed. It looks like it is properly sorting items from newest on the top to oldest on the bottom. The only thing I see from a code perspective is that the API is not returning individual devotions. The `byUserFeed` function just isn't returning `ContentChannelId eq 1`. I can easily add that and PR if you guys feel like we need/want it. 

Other than that, this feels good. 

The only other thing I'd mention is that the task says "...possibly giving the church some control over what items appear in the home feed." This sounds like maybe implementing "topics"? Or if we're talking about giving the church as a whole the ability to show or hide whole content channels, then I think we might need to possibly look at updating the content channels in Rock to have an "active" flag of some sort and then implementing that into the API. Then a church could turn off whole content channels from being shown in the app. But both of those things sound like they are out of the scope of the 4 point estimate assigned to this task. 

Thoughts?

**Comment by conrad-vanl** [comment]
Nah, I don't think this needs any more attention right now. Thanks for digging in!
