### ISSUE TITLE
Liking content

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#164]
## User Story

A user can like content

#### Problem Details _(Optional)_

* Screenshots, GIFs, or a video
* Any additional information (version, device, etc.)

#### Acceptance Criteria _(Optional)_

* [ ] It should [SPEC_DETAIL]

**Comment by IsaacHardy** [comment]
Closing because it sucks.

**Comment by vinnyjth** [comment]
🔥 🔥 🔥 🔥
