### ISSUE TITLE
View events in the app

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#169]
## User Story

A user can view a list of events in the app

#### Problem Details _(Optional)_

* Screenshots, GIFs, or a video
* Any additional information (version, device, etc.)

#### Acceptance Criteria _(Optional)_

* [ ] It should [SPEC_DETAIL]

**Comment by vinnyjth** [comment]
Wow @conrad-vanl. Old but 🏅

**Comment by vinnyjth** [comment]
Implemented in #1059
