### ISSUE TITLE
Apollos UI Storybook

### ISSUE THREAD

**Issue by burkeshartsis** [ApollosProject/apollos-prototype#18]
## User Story

As an engineer I want to be able to examine the api and state of a component so that I can better use Apollos UI components in the Apollos Church prototype app.

#### Acceptance Criteria _(Optional)_

- [ ] Setup a basic Storybook using best practices.
- [ ] Configure React Native Storybook loader.

**Comment by burkeshartsis** [comment]
@conrad-vanl what do you think about using [Storyshots](https://github.com/storybooks/storybook/tree/master/addons/storyshots)?

**Comment by IsaacHardy** [comment]
@burkeshartsis Storyshots looks really useful and easy to setup. I'm about to start on implementing unit tests into the app's CI and wouldn't mind the setup of Storyshots, either.
