### ISSUE TITLE
Design GraphQL schema for ESV scripture 

### ISSUE THREAD

**Issue by IsaacHardy** [ApollosProject/apollos-prototype#182]
#### Problem Details _(Optional)_

For this issue, we need to design a GraphQL schema that pulls in a set of scripture from an ESV version API. We can look into other options, but we used "http://www.esvapi.org" in Heighliner. 

#### Acceptance Criteria _(Optional)_

* [ ] Should be able to retrieve html for a specified verse.

**Comment by conrad-vanl** [comment]
I think we can totally port the functionality over that we had in [Heighliner](https://github.com/newspring/heighliner). We probably want to tweak the schema slightly when we port over. @vinnyjth has a lot of experience with bible apis too, so I'm sure he'll have insight

For clarity, we built a [`<Scripture>` component](https://github.com/NewSpring/Apollos/tree/alpha/src/%40ui/Scripture) in the original NewSpring project. It takes in a scripture reference, that looks like "Genesis 1:1-10", "Matthew 5", etc, queries the graphql api for scripture html (in ESV's html format), and renders it. The rendering of ESV's HTML into React Native was fairly well tested, and I think still makes sense for the place to start.

I totally think long-term we should consider how best to work with Scripture... There might be integrations we could tap with The Bible App / Life.Church as well ... like, as a low-hanging-fruit, it'd be cool IMO if we had an "Open in The Bible App" button with scripture, which I'm sure we could figure out how to do. That also might help bridge the lack of multi-translation support temporarily.

(Ie....Opening this link on your phone _should_ take you straight to the bible app at John 1:11: https://www.bible.com/bible/1/JHN.1.11)

**Comment by conrad-vanl** [comment]
Leaving this thought here as well: I'm pretty sure that Heighliner uses a now deprecated version of the ESV API. We'd want to look into upgrading to the newest version.
