### ISSUE TITLE
Refactor local `imports` to use absolute paths. 

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-prototype#184]
## User Story

As a developer I want to use absolute imports so that I don't have to keep track of complex path traversal. 

#### Problem Details _(Optional)_

https://github.com/ApollosProject/apollos-prototype/blob/master/api/src/connectors/rock/Model.js#L1
```
import { createCursor, parseCursor } from '../../utils/cursor';
// should become
import { createCursor, parseCursor } from 'app/utils/cursor';
```

https://spin.atomicobject.com/2017/10/07/absolute-paths-javascript/
https://github.com/facebook/react-native/issues/3099#issuecomment-221815006
https://github.com/tleunen/babel-plugin-module-resolver

#### Acceptance Criteria

- [ ] Eliminate use of `../..` in the API

**Comment by conrad-vanl** [comment]
@vinnyjth we implemented this on the `/mobile` side, and can likely use the same package to do so (or, if you have a better way, just as long as both are consistent :) )
