### ISSUE TITLE
Setup app wide media player state in app

### ISSUE THREAD

**Issue by burkeshartsis** [ApollosProject/apollos-prototype#191]
## User Story

As an app user I want a seamless and integrated video and audio experience so that the app does not distract me from the content.

#### Problem Details _(Optional)_

* Screenshots, GIFs, or a video
* Any additional information (version, device, etc.)

#### Acceptance Criteria _(Optional)_

* [ ] It should [SPEC_DETAIL]

**Comment by conrad-vanl** [comment]
I'd love to help out on this 😄
