### ISSUE TITLE
Formalize a standard for inline commenting / documentation

### ISSUE THREAD

**Issue by richarddubay** [ApollosProject/apollos-prototype#192]
## User Story

As a developer, I want to have a standard for inline commenting / documentation so that I can write helpful, automatically generated documentation for myself and others.

#### Acceptance Criteria

* [ ] It should follow a popular DOCGEN standard.
* [ ] It should be documented in the main `apollos-prototype` README.
* [ ] It should have some beginning documentation already set up (if the solution is NOT Storybook).

**Comment by richarddubay** [comment]
@conrad-vanl @burkeshartsis 

The goal of this task (unless I misunderstood it) was to come up with a standard for inline commenting so that we can write helpful, automatically generated documentation.

To that end, I conducted research of some of the big players in our industry to see how they were creating their online documentation. It turns out that the majority of them (including Facebook/React Native, Jest, and Apollo) use separate Markdown files for their documentation. They then use a service like [Docusaurus](https://docusaurus.io/) to render those files to a static site. 

While this is cool, I don’t feel like it completely fits what we were looking for. The need for inline comments kind of necessitates a different approach.

So I propose that we move to a [JSDoc](http://usejsdoc.org/index.html) model of documentation. I think this will allow us to have great inline documentation in our code and then give us a head start should we ever decide that we want to automatically create documentation using something like React Styleguidist or a similar tool. We could definitely still combine this with Markdown files for additional documentation should we feel like there is a need. 

Thoughts? What am I missing?

**Comment by burkeshartsis** [comment]
This might be helpful. The issue covers why storybook info-addon doesn't work. How close it is to being fixed but not yet 😭 and some alternatives to use in the interim.

https://github.com/storybooks/storybook/issues/1147#issuecomment-305114066

**Comment by richarddubay** [comment]
@burkeshartsis I actually read through this the other day! 🎉 

It sounds like they want to get something in the works after they release 4.0: https://github.com/storybooks/storybook/issues/1147#issuecomment-411444930
