### ISSUE TITLE
Add URL and Message/Description Items to Graph.

### ISSUE THREAD

**Issue by richarddubay** [ApollosProject/apollos-prototype#206]
## User Story

As a developer I want to have URL and message/description data passed in through the Graph so that I can share the most accurate information.

#### Problem Details _(Optional)_
Right now we only have the title of a content item being passed down through the graph. For sharing, we also need at least one of a URL or Message/Description. Ideally both.

#### Acceptance Criteria _(Optional)_

* [ ] It should pass down URL and message/description data for content items.

**Comment by vinnyjth** [comment]
@richarddubay this is something I can tackle!

**Comment by vinnyjth** [comment]
Ping @conrad-vanl before I start
