### ISSUE TITLE
Basic Apollos UI theme/typography API

### ISSUE THREAD

**Issue by burkeshartsis** [ApollosProject/apollos-prototype#21]
## User Story

As an engineer I want to setup a basic Apollos UI theme, style, and typography API so that I can create visually consistent interfaces in the Apollos Church prototype app.

#### Problem Details _(Optional)_
- Move [styled](https://github.com/NewSpring/Apollos/tree/alpha/src/%40ui/styled) and [theme API](https://github.com/NewSpring/Apollos/tree/alpha/src/%40ui/theme) from Newspring-Apollos as is.
- Consider setting up UI, title, and body typographic structure.
- Possible sans serif typefaces
  - [Inter UI](https://github.com/rsms/inter)
  - [Open Sans](https://fonts.google.com/specimen/Open+Sans)
  - [Fira Sans](http://mozilla.github.io/Fira/)
  - System fonts
- Possible serif typefaces
  - [Droid Serif](https://typekit.com/fonts/droid-serif)

**Comment by conrad-vanl** [comment]
Time permitting, I think my top vote would go towards a three family solution:

1. system fonts for UI text
2. Fira or Inter for headings
3. Droid for serif text

My secondary vote would go towards the most time efficient solution for:

1. system fonts for sans-serif (OR inter ui or open sans)
2. droid for serif text

**Comment by burkeshartsis** [comment]
@conrad-vanl do you see there being a difference in typeface for headings and content if break out ui text into it's own family? I miscounted that would mean a 4 font solution including serifs.
