### ISSUE TITLE
Add scripture component to the devotional content items and bring in the scripture tab.

### ISSUE THREAD

**Issue by cdanwards** [ApollosProject/apollos-prototype#219]
## User Story

As a user I want to be able to see the context of scripture references in my devotionals so that I can better understand the scripture and devotion.

#### Problem Details _(Optional)_

* Screenshots, GIFs, or a video
* Any additional information (version, device, etc.)

#### Acceptance Criteria _(Optional)_

* [ ] It should correctly display in the Devotional and be able to tab over to full scripture reference.

**Comment by IsaacHardy** [comment]
Removing in favor of #244
