### ISSUE TITLE
[Scripture] Design and develop viewable scripture within content

### ISSUE THREAD

**Issue by IsaacHardy** [ApollosProject/apollos-prototype#247]
This issue will consist of designing and developing the scripture component to content. The functionality should consist of a switchable view between an article and related scripture similar to how the NewSpring Apollos app current displays them. 

If it is determine that certain API changes need to be made, we can create a separate issue to address them.

#### Acceptance Criteria _(Optional)_

* [ ] A user can view scripture that is related to a specific devotional
* [ ] A user can switch between the devotional text and the scripture

**Comment by richarddubay** [comment]
I broke this up into a couple different issues for this coming sprint. So I'm going to close this one in favor of those.
