### ISSUE TITLE
Investigate possible media casting functionality

### ISSUE THREAD

**Issue by burkeshartsis** [ApollosProject/apollos-prototype#250]
## User Story

As a `<type of user>` _(who)_ I want to `<perform an action>` _(what)_ so that I can `<achieve a goal>` _(why)_.

#### Problem Details _(Optional)_

- platform specific casting (ios = airplay, android = google cast)
- bonus points for google on both 💥

#### Acceptance Criteria _(Optional)_

* [ ] It should [SPEC_DETAIL]

**Comment by burkeshartsis** [comment]
possibly the most straight forward ios solution. https://github.com/disjfa/react-native-airplay-btn

**Comment by burkeshartsis** [comment]
related way to possibly improve the airplay UX a bit in app.

https://github.com/react-native-community/react-native-video/blob/639f2bbd4cf7da89d303adc5f29af1a2c167a87e/Video.js#L377

**Comment by redreceipt** [comment]
https://github.com/react-native-google-cast/react-native-google-cast

**Comment by conrad-vanl** [comment]
@redreceipt open a PR for your branch and then we can close this issue :)

**Comment by redreceipt** [comment]
#422
