### ISSUE TITLE
Connect tab UI/UX polish

### ISSUE THREAD

**Issue by burkeshartsis** [ApollosProject/apollos-prototype#277]
## User Story

As an app user I want to be focused on what matters so that I connect with God and grow within my church community.

#### Acceptance Criteria 

- [ ] all the things

**Comment by conrad-vanl** [comment]
![image](https://user-images.githubusercontent.com/103927/46085565-ef954a00-c16b-11e8-8ec9-8cc0bfffe43b.png)
