### ISSUE TITLE
[Push Notifications] Set up the RN Firebase Cloud Messaging

### ISSUE THREAD

**Issue by cdanwards** [ApollosProject/apollos-prototype#279]
As a developer / administrator, I want to be able to send out important / pertinent info to users of my app.

#### Problem Details _(Optional)_

* Screenshots, GIFs, or a video
* Any additional information (version, device, etc.)

#### Acceptance Criteria _(Optional)_

* [ ] It should be able to handle a push notification when opened.

**Comment by vinnyjth** [comment]
Closing this in place of the OneSignal implementation.
