### ISSUE TITLE
[User Profile] Profile settings - Change Password

### ISSUE THREAD

**Issue by IsaacHardy** [ApollosProject/apollos-prototype#287]
## User Story

A user can change their password from their User Profile Settings Menu.

#### Problem Details _(Optional)_

* Screenshots, GIFs, or a video
* Any additional information (version, device, etc.)

#### Acceptance Criteria _(Optional)_

* [ ] A user can change their password

**Comment by conrad-vanl** [comment]
![image](https://user-images.githubusercontent.com/103927/46085384-8a415900-c16b-11e8-8849-73aaf61721c2.png)

Here's where we're going to move forward with in the short term.
