### ISSUE TITLE
[User Profile] Profile Fields Updating Interface

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-prototype#295]
## User Story

As a  logged in user, I should be able to update my First Name and Last Name. 

API work completed in #260 

#### Problem Details _(Optional)_

* Screenshots, GIFs, or a video
* Any additional information (version, device, etc.)

#### Acceptance Criteria _(Optional)_

* [ ] It should [SPEC_DETAIL]

**Comment by conrad-vanl** [comment]
![image](https://user-images.githubusercontent.com/103927/46085384-8a415900-c16b-11e8-8849-73aaf61721c2.png)

Here's where we're going to move forward with in the short term.
