### ISSUE TITLE
Implement an Image CDN

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#338]
## User Story

As a user I want images in the app to load quickly and not consume more bandwidth then needed!

#### Problem Details _(Optional)_

Images are pretty slow loading in the app. They are currently rock endpoints. Supposedly, Rock has the ability to do some basic image manipulation using query parameters, but not sure if there's documentation on that.

So, HMW do a "less, but better" image service for Apollos? In the past, we've used something like Cloudinary or Imgix. Those are easy, fast, and can be affordable if configured well. For Apollos, I think both of those would be super easy to implement - just embed our current Rock urls inside of a cloudinary/imgix url and the service will handle the rest. Can all be done on the graphql side.

I think priority is stability and speed, with secondary concern on cost. 

Thoughts?

#### Acceptance Criteria _(Optional)_

* [ ] It should [SPEC_DETAIL]

**Comment by vinnyjth** [comment]
> I think priority is stability and speed, with secondary concern on cost.

Given those constraints, I would pick Cloudinary :) They have a free tier that may stay free for most of the churches. They are easy to implement. I've experienced they their performance is a tad worse than Imgix at times, and potentially cheaper at massive scale, but I don't think we will run into any of those factors as constraints.
