### ISSUE TITLE
Keyboard hiding form's fields UX

### ISSUE THREAD

**Issue by burkeshartsis** [ApollosProject/apollos-prototype#370]
## User Story

As a `<type of user>` _(who)_ I want to `<perform an action>` _(what)_ so that I can `<achieve a goal>` _(why)_.

#### Problem Details

> "While typing, can't see the [login] field I'm typing in. Keyboard covers all fields, and the copy at the top covers the top half of the screen." – @vinnyjth 

#### Acceptance Criteria _(Optional)_

* [ ] It should [SPEC_DETAIL]

**Comment by conrad-vanl** [comment]
Might need design changes due to size of non-scrolling portion of view
