### ISSUE TITLE
HorizontalTileFeed missing/inconsistant paddingRight

### ISSUE THREAD

**Issue by burkeshartsis** [ApollosProject/apollos-prototype#378]
## User Story

As a `<type of user>` _(who)_ I want to `<perform an action>` _(what)_ so that I can `<achieve a goal>` _(why)_.

##### Discover tab
<img src="https://user-images.githubusercontent.com/2053547/47875773-c9f40400-dded-11e8-87b1-6a2a137d9f45.png" width="50%" />

##### Sermon Series
<img src="https://user-images.githubusercontent.com/2053547/47876421-ae89f880-ddef-11e8-9d45-6f1dc1b86dca.png" width="50%" />

#### Acceptance Criteria _(Optional)_

* [ ] It should [SPEC_DETAIL]

**Comment by cdanwards** [comment]
![Screen Shot 2019-03-18 at 4 19 28 PM](https://user-images.githubusercontent.com/8878532/54560864-ad6df800-4999-11e9-832d-a4f7562996c7.png)


@burkeshartsis it looks like through other re-factors that this is no longer an issue. I'll move this issue to review.

**Comment by burkeshartsis** [comment]
@dan 🤷‍♂️ The screenshots above are from the Discover and Sermon Series pages. Can you check those. Your screenshot is the profile tab. Are they all fixed already?

**Comment by cdanwards** [comment]
<img width="403" alt="Screen Shot 2019-03-19 at 9 09 30 AM" src="https://user-images.githubusercontent.com/8878532/54608343-dee0d500-4a26-11e9-86a5-9ff68a6a6ea6.png">
<img width="389" alt="Screen Shot 2019-03-19 at 9 10 03 AM" src="https://user-images.githubusercontent.com/8878532/54608347-e1432f00-4a26-11e9-8d34-99f9c95eb089.png">


@burkeshartsis looks like it's fixed there as well.

**Comment by burkeshartsis** [comment]
Hey noting better than issues that close themselves.

<img src="https://media.giphy.com/media/6brH8dM3zeMyA/giphy.gif" />

Closing as it's apparently no longer an issue.
