### ISSUE TITLE
[Android] "View All" hitSlop on Discover tab is hard to tap (too small)

### ISSUE THREAD

**Issue by burkeshartsis** [ApollosProject/apollos-prototype#379]
## User Story

As a `<type of user>` _(who)_ I want to `<perform an action>` _(what)_ so that I can `<achieve a goal>` _(why)_.

#### Problem Details _(Optional)_

* Screenshots, GIFs, or a video
* Any additional information (version, device, etc.)

#### Acceptance Criteria _(Optional)_

* [ ] It should [SPEC_DETAIL]

**Comment by conrad-vanl** [comment]
https://facebook.github.io/react-native/docs/touchablewithoutfeedback#hitslop
