### ISSUE TITLE
Setup release plan for release 1

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#38]
#### Acceptance Criteria

* [ ] Setup release plan to be used for release 1 at end of sprint 2
* [x] Distribution of mobile build
* [x] Hosting of API

**Comment by conrad-vanl** [comment]
my requirements are loosely defined as being able to say "we did it!", "we can do this again!" and "we can show this to partners". But more technically, I'd like to see:

- versioning that follows [semantic versioning](https://semver.org/)
- calling this like a pre-alpha release or something
- versioning should start with like 0.0.1 or something
- look into using git tags to signify the release in github https://help.github.com/articles/creating-releases/
- Create a changelog.md file to document changes in this release (or add them to the release notes in the above link)
- Distribution of the release via staged phases: test/internal distribution in appcenter and ability to promote to testflight / google play beta

For release 1, this is all meant to test the process so we can make it smoother when we want to do more public releases. If we can't get to testflight/google play beta distribution that's OKAY - as long as we can identify steps to get there in the future.

**Comment by conrad-vanl** [comment]
@IsaacHardy another thought on this. Since now.sh makes deployments to unique URLs every deploy, is there a way we can make that build of the app point to that unique URL? Right now I believe we will likelyt be introducing breaking changes to the API, and if a build can point at the version that now was deployed to, that would help make sure are builds stay working for now. 

It would be a matter of changing `APP_DATA_URL` to the correct now.sh deployment.

I think long-term this may not be what we want to do (as we should assert backwards compatibility in our graphql schema), but it might make sense short term if there's a way to do it.

**Comment by IsaacHardy** [comment]
@conrad-vanl I'll look into a way to accomplish this.

**Comment by IsaacHardy** [comment]
Looks like in the [documentation](https://zeit.co/docs/features/env-and-secrets), there is a `NOW_URL` after a build is successful. I'm looking into a way to harness that variable.

**Comment by conrad-vanl** [comment]
We could always go about it the other way - make the URL we alias the now build with an alias the includes the build number (or `git tag`) or something like that

**Comment by conrad-vanl** [comment]
then we can generate the URL ourselves without relying on Now to expose it

**Comment by conrad-vanl** [comment]
and @IsaacHardy lets do a code lock on friday and build on monday

**Comment by IsaacHardy** [comment]
I like that idea and sounds good.
