### ISSUE TITLE
Sermon/Devotional horizontal series feed ordering and UX issues

### ISSUE THREAD

**Issue by burkeshartsis** [ApollosProject/apollos-prototype#381]
## User Story

As a `<type of user>` _(who)_ I want to `<perform an action>` _(what)_ so that I can `<achieve a goal>` _(why)_.

#### Problem Details _(Optional)_

* Screenshots, GIFs, or a video
* Any additional information (version, device, etc.)

#### Acceptance Criteria _(Optional)_

Blockers:

* [ ] HorizontalTileFeed should include the sermon/devotional currently being viewed
* [ ] HorizontalTileFeed should be ordered from first to last in the series

---

+1's:

* [ ] HorizontalTileFeed should auto scroll to the sermon/devotional currently being viewed
* [ ] Devotionals should render a single HorizontalTileFeed or keep the two that are rendered in each tab in sync.

**Comment by vinnyjth** [comment]
Wow, we already had an issue for this! 
Same as #958 
Closed in #983
