### ISSUE TITLE
Profile tab recent like query issues

### ISSUE THREAD

**Issue by burkeshartsis** [ApollosProject/apollos-prototype#384]
## User Story

As a `<type of user>` _(who)_ I want to `<perform an action>` _(what)_ so that I can `<achieve a goal>` _(why)_.

#### Problem Details _(Optional)_

* Screenshots, GIFs, or a video
* Any additional information (version, device, etc.)

#### Acceptance Criteria _(Optional)_

* [x] Only shows three tiles
* [x] Updates with new like/unlikes

**Comment by vinnyjth** [comment]
Completed as of #568
