### ISSUE TITLE
User Avatar uploading inconsistencies

### ISSUE THREAD

**Issue by burkeshartsis** [ApollosProject/apollos-prototype#385]
## User Story

As a `<type of user>` _(who)_ I want to `<perform an action>` _(what)_ so that I can `<achieve a goal>` _(why)_.

#### Problem Details _(Optional)_

> "loading icon appeared for a bit but eventually went away. new photo never appeared. Navigating back a screen and forward makes the photo appear." – @burkeshartsis 

> "loading dialogue appears over old photo, but new photo never appears even after loading dialogue goes away. If i quit the app and come back, old photo is still there" – @conrad-vanl 

#### Acceptance Criteria _(Optional)_

* [ ] It should [SPEC_DETAIL]

**Comment by conrad-vanl** [comment]
Look at cloudinary, appears to be caching related

**Comment by conrad-vanl** [comment]
Closed by #429
