### ISSUE TITLE
[INTEGRATION] Create NewSpring app prototype

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#396]
Creating this as an epic. We can add sub-issues to this as they get created

## User Story

As a `<type of user>` _(who)_ I want to `<perform an action>` _(what)_ so that I can `<achieve a goal>` _(why)_.

#### Problem Details _(Optional)_

* Screenshots, GIFs, or a video
* Any additional information (version, device, etc.)

#### Acceptance Criteria _(Optional)_

* [ ] It should [SPEC_DETAIL]

**Comment by IsaacHardy** [comment]
@conrad-vanl I believe we can close this.
