### ISSUE TITLE
Sermon Series Clicks Layers On Itself and Gets Slow

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#407]
## User Story

As a `<type of user>` _(who)_ I want to `<perform an action>` _(what)_ so that I can `<achieve a goal>` _(why)_.

#### Problem Details _(Optional)_

When you click through to different sermon series cards from each other, they layer on top of each other and get extremely laggy. Also, you have to back all the way out.

![20181105_165039](https://user-images.githubusercontent.com/2659478/48028992-15beea00-e11b-11e8-9c63-2209b544e89a.gif)

* Screenshots, GIFs, or a video
* Any additional information (version, device, etc.)

#### Acceptance Criteria _(Optional)_

* [ ] It should [SPEC_DETAIL]

**Comment by conrad-vanl** [comment]
`react-native-screens` should be able to fix this, or atleast make it better: https://reactnavigation.org/blog/2018/11/17/react-navigation-3.0.html

So maybe we attempt an upgrade to react-navigation 3.0?

**Comment by redreceipt** [comment]
Also, I feel like the previous devotion should be popped off the stack. So instead of:

1 -> 2 -> 3 making the stack [1,2,3]

it should be: 

1 -> 2 -> 3 results in [1,3]

**Comment by redreceipt** [comment]
seems to be fixed!
