### ISSUE TITLE
Sermon Series Trailer Doesn't Play

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#408]
## User Story

As a `<type of user>` _(who)_ I want to `<perform an action>` _(what)_ so that I can `<achieve a goal>` _(why)_.

#### Problem Details _(Optional)_
![20181105_165841](https://user-images.githubusercontent.com/2659478/48029480-45babd00-e11c-11e8-8239-073d453bc36d.gif)

* Screenshots, GIFs, or a video
* Any additional information (version, device, etc.)

#### Acceptance Criteria _(Optional)_

* [ ] It should [SPEC_DETAIL]

**Comment by conrad-vanl** [comment]
- [ ] Document reproduction steps / make sure still an issue

**Comment by redreceipt** [comment]
@conrad-vanl reinstalled and can't reproduce now. Closeable I think.
