### ISSUE TITLE
Tapping Profile Photo To Edit

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#410]
## User Story

As a `<type of user>` _(who)_ I want to `<perform an action>` _(what)_ so that I can `<achieve a goal>` _(why)_.

#### Problem Details _(Optional)_

Tapping the profile photo on the profile settings should also allow me to edit the photo. It's more inituitive. or maybe just show a large version. either way, it should be clickable.

![screenshot_20181106-094457](https://user-images.githubusercontent.com/2659478/48071605-b60f2000-e1a8-11e8-8eda-fb0ae5961b0f.png)

* Screenshots, GIFs, or a video
* Any additional information (version, device, etc.)

#### Acceptance Criteria _(Optional)_

* [ ] It should [SPEC_DETAIL]

**Comment by conrad-vanl** [comment]
Closed by #401
