### ISSUE TITLE
Create documentation project in GH

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#480]

**Comment by vinnyjth** [comment]
I believe we already have this done. Can you confirm @redreceipt ?

**Comment by redreceipt** [comment]
@vinnyjth I think @conrad-vanl is talking about creating a Github project to track stuff. 

![Screen Shot 2019-04-24 at 9 52 44 AM](https://user-images.githubusercontent.com/2659478/56664799-c8a5e480-6676-11e9-85e3-39d48c02e286.png)

**Comment by conrad-vanl** [comment]
🤔

**Comment by conrad-vanl** [comment]
> No description provided.

🤦‍♂️ 🤕

**Comment by vinnyjth** [comment]
Closing by EoD today unless anyone speaks up otherwise 😂
