### ISSUE TITLE
[API] Standardize on location of schema/resolvers/dataSource

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-prototype#481]
Some resolvers/schemas in some modules are located in the `index.js` of the module, while others are located in a `resolvers.js` or `schema.js`. We should standardize on all files being split up into `resolvers.js` and `schema.js`.

**Comment by conrad-vanl** [comment]
@vinnyjth how is this going? (I'm gearing up for sprint planning today and auditing our remaining issues)

**Comment by vinnyjth** [comment]
Started on it, but didn't get anything pushed up yet. You can move it back to "Not Started"
