### ISSUE TITLE
Create a Mobile Passes schema for users

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#485]
## User Story

As a `user` I want to `access my mobile passes` so that I can `check-in` to physical installations hosted by my Church.

#### Acceptance Criteria

* [ ] It should provide a list of passes

**Comment by conrad-vanl** [comment]
@vinnyjth taking a first pass at writing an initial set of GQL types. The goal is to expose enough information about a pass to display this screen in app:

![image](https://user-images.githubusercontent.com/103927/51992515-bbf86280-2472-11e9-823b-2ddf2f6fd5c6.png)

However, I'm structuring the GQL types similar to what is required by Apple to generate a pass. Here's where I'm at so far. This supports a minority subset of the pass fields:

```gql
type Pass {
  type: PassType!
  description: String!
  primaryFields: [PassField]
  secondaryFields: [PassField]
  backgorundColor: Color
  foregroundColor: Color
  labelColor: Color
  logoText: String
  serialNumber: String
  barcode: PassBarcode
  locations: [PassLocation]
  passkitFileUrl: String
}

type PassField {
  key: String!
  label: String
  value: String!
  textAlignment: PassFieldTextAlignment
}

type PassBarcode {
  message: String!
  format: PassBarcodeFormat!
  messageEncoding: PassBarcodeMessageEncoding!
}

enum PassFieldTextAlignment {
  LEFT
  CENTER
  RIGHT
  NATURAL
}

enum PassBarcodeFormat {
  QR
  PDF417
  Aztec
}

enum PassBarcodeMessageEncoding {
  ISO88591
}

enum PassType {
  GENERIC
}
```

So, the idea is to use this schema to expose a list of `Passes` that the app can display. It uses this schema to render a version of the pass in-app, then offers a "Add to Wallet" button at the bottom that utilizes the `passkitFileUrl` attribute (which links to the `pkpass` file that we can generate with [this library](https://www.npmjs.com/package/passkit-generator)).

One potential bottleneck I'm trying to think through is how we want to render barcodes. Right now, this schema assumes we can render the barcode natively on the client. Initial research shows that this is doable, but will require separate NPM packages to support both 2D and 3D barcodes. We'd essentially rely on `react-native-svg` and a barcode support library. There's a couple of `react-native` packages that already do this that are fairly simple. I can likely get the churches to agree on using only 2D or 3D barcodes for MVP. But...the other thought is if we should generate an image on the server side and just let the client display the image. 

The other problem I'm thinking through: generation of `pkpass` files. Using that `passkit-generator` library we could generate passes on the fly...but we do need to be able to offer a URL that they can be downloaded from. Is that something we can tie into the CDN-caching you're doing? It would be a non-graphql url....I'm thinking we could create some sort of REST endpoint on the `-api` server that just responds with the generated `pkpass` file....thoughts?

**Comment by vinnyjth** [comment]
> But...the other thought is if we should generate an image on the server side and just let the client display the image.
This would probably be easier to do on the server than it would be on the client, theres about a million and one node libraries for generating barcodes on the fly with or without native binaries. 

We could do something like 
```
type PassBarcode {
  message: String!
  format: PassBarcodeFormat!
  messageEncoding: PassBarcodeMessageEncoding!
  imageUri: String!
}
so that both are available? 

> The other problem I'm thinking through: generation of pkpass files. Using that passkit-generator library we could generate passes on the fly...but we do need to be able to offer a URL that they can be downloaded from. Is that something we can tie into the CDN-caching you're doing? It would be a non-graphql url....I'm thinking we could create some sort of REST endpoint on the -api server that just responds with the generated pkpass file....thoughts?

Fastly would totally cache this by default :). I think exposing a `rest` endpoint is probably the best path forward. We could technically create a GraphQL `GET` link that would return a JSON object with the Pkpass embeded in it, but it would probably be easier and work better if we it just exposed a `/pkpass/${userId}` endpoint that accepts the same auth token our client did. 

Besides that, your schema looks really good. I have one idea (which I imagine you have already thought about) 

What do you think about styling inline (like you are doing now) vs having predefined styles based on the PassType. Styling inline is certainly more flexible, and I like that you wouldn't need to return a new version of the app to create a new pass style. However, do you think it would be needlessly complex? If not, I really like the schema you designed for styling. It's very straightforward and should be pretty easy to implement.

**Comment by conrad-vanl** [comment]
So the styling in graphql mimics the styling parameters required for pkpass files - which would exist on the API side anyways - https://developer.apple.com/library/archive/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/TopLevel.html

I think the REST endpoint would end up being something like

`/pkpass/${passTemplate}`

If we have an authentication token included, we probably don't need to have the `userId` in the url!

I do question the Auth side of it. If you look at that link above, and scroll down...you can see that we can encode the URL that the pass "lives" at, as well as an `authenticationToken`. This is used if we ever want to support auto-updating passes. I think this would work though?
