### ISSUE TITLE
[LOCATION FINDER] Create MapView component that shows locations on a map and sets center point to user's current location

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#522]
MapView should look something like this (can focus on just the map for now):

https://sketch.cloud/s/xj5vl/oYgbMMx

Perhaps we use this? https://github.com/react-native-community/react-native-maps Other suggestions?

Could also look into using Expo's module, I believe their SDK is compatible with non expo apps now

**Comment by cdanwards** [comment]
@conrad-vanl I'm going to go ahead and jump into this. I've looked and the react-native-maps seems to be the only package with good support, so I'll give that a try and if there's a snag we can reevaluate.
