### ISSUE TITLE
Add custom icon support to `<Icon />`

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#549]
This can probably be done through theme or by creating an `IconProvider` type component where you pass an icon set into that `<Icon />` reads from.

Also, since there's no good open-source svg-based `react-native` `<Icon />` component, we might consider moving our Icon work into a separate package, perhaps even separate repo with a standard open source license. It'd be good for the larger RN community.

**Comment by conrad-vanl** [comment]
Should make sure we implement an mvp-focused/less-but-better approach on this.

As in...I don't believe we need to start with a tool that converts an SVG to React component (unless something like that exists that we can just re-implement). But more or less make sure that we have a way to define Icons that the Icon component can utilize.

Ideally, this icon set is something that even instances of the `<Icon />` component that exists in our core components would use. In other words, you can specify a _new_ `arrow-right` icon and that icon is used everywhere.

This probably needs we need to create a `<IconsetProvider />` type component or somehow shove the icon set into the theme.

**Comment by redreceipt** [comment]
Love it. So tell me if this makes sense. I'm trying to think of it from the devs perspective. Have a folder full of SVGs or PNGs anywhere you want in your tree and then we create something like:

```jsx
<IconSet source={'./icons'}>
    <Icon name={'arrow-right'} />
</IconSet>
```

Constrained only by unique filenames. Seems like an easily acceptable rule.

**Comment by conrad-vanl** [comment]
Instead of passing in the folder, you'll likely pass in an object of `React` components, like we do on the icon component [here](https://github.com/ApollosProject/apollos-prototype/blob/master/packages/apollos-ui-kit/src/Icon/index.js#L8)... but yes - I think it would work something like that.

**Comment by redreceipt** [comment]
to be adopted and useful by the wider community, wouldn't you think we just pass in images? Or is that something to work on later?

**Comment by conrad-vanl** [comment]
passing in `React` components allow you to use SVGs, Images, whatever. The problem is that Icons don't work well as images, and is not something we want to promote. Eventually, we can have a tool that takes SVGs and spits out react components (which we've built before)

**Comment by redreceipt** [comment]
I guess my question is why shouldn't we just create this:

```jsx
<Icon source={'./icon.svg'} />
```

**Comment by redreceipt** [comment]
...or just use this?

Alternatively, you can use `react-native-svg-uri` with `babel-plugin-inline-import`, but with transforms done at run-time.

`.babelrc`

```
{
  "presets": ["module:metro-react-native-babel-preset"],
  "plugins": [
    ["babel-plugin-inline-import", {
      "extensions": [
        ".svg"
      ]
    }]
  ]
}
```

`App.js`

```jsx
import * as React from 'react';
import SvgUri from 'react-native-svg-uri';
import testSvg from './test.svg';
export default () => (
  <SvgUri
    width="200"
    height="200"
    svgXmlData={testSvg}
  />
);
```

**Comment by conrad-vanl** [comment]
I think an individual app could do any of these, and we could evaluate either of those import options as what's in the default template. But at the end of the day, all that the `Icon` component does is render a react component and passes it certain props of a specific api design. We need to open that functionality up, and then whether a church (and the default template) uses inline imports, svg-uri package, etc becomes very simple.

**Comment by redreceipt** [comment]
@burkeshartsis are you taking this one?

**Comment by burkeshartsis** [comment]
@redreceipt I'm looking into this a bit is all. Exploring some ideas via the theme provider.

**Comment by redreceipt** [comment]
Love it. I definitely think theme is the way to go too. I'm gonna pull
myself off. If you come up with a solid plan and would like me to implement
it, just stick me back on there.

--
Michael Neeley
Junior Web Developer
NewSpring Church
www.newspring.cc
Cell: (803) 622-6599

**Comment by burkeshartsis** [comment]
current plan

1. Import a folder of custom icons via the theme provider (but not accessible to the theme) to be passed to `Icon`.
2. Benchmark memory footprint so @conrad-vanl and @vinnyjth will let me make this better 😉 
3. Try a lazy loading approach with "dynamic `require`s" or `react.lazy` and bench mark again.
