### ISSUE TITLE
[Onboarding] Create age and birthday screen

### ISSUE THREAD

**Issue by burkeshartsis** [ApollosProject/apollos-prototype#551]
## User Story

As a first time app user I want to personalize my app experience while exploring what is available to me so that I can grow spiritually in a purposeful and missional way.

#### Problem Details

* Blocked by #536 
* This is the third screen in the onboarding flow.
* https://sketch.cloud/s/YJ3xZ/4aAWKrx
* There may need to be some discussion around the radio input for gender. Will churches need more than two options? Is our current radio component good enough for MVP?

#### Acceptance Criteria

* [ ] It should render as a component that can be used elsewhere in the app.
* [ ] It should take a custom title
* [ ] It should take a custom description.
* [ ] The text in the screenshot can be considered default values
* [ ] It should display a custom image

**Comment by redreceipt** [comment]
@burkeshartsis trying to use `DateInput` and `RadioButton` here but I don't know how to use the components. High-level summary? What props are required?

**Comment by burkeshartsis** [comment]
I don't believe our UI kit `Radio` input is anything like the one in the mock. We should probably talk that over with @conrad-vanl to see how he wants to proceed.

I'm not super familiar with the component either. You can probably find a similar working example somewhere in NS Apollos. That said, while `DateInput` is lacking a story and explicit documentation tests – if thorough and written well – can usually tell you everything you need to know. Looks like at least some of the props are covered [there](https://github.com/ApollosProject/apollos-prototype/blob/master/packages/apollos-ui-kit/src/inputs/DateInput/DateInput.tests.js) or at least the ones that will get the component to render something.
