### ISSUE TITLE
[Onboarding] Build out onboarding screen 2

### ISSUE THREAD

**Issue by burkeshartsis** [ApollosProject/apollos-prototype#553]
## User Story

As a first time app user I want to personalize my app experience while learning exploring what is available to me so that I can grow spiritually in a purposeful and missional way.

#### Problem Details

* Blocked by #536 
* This is second screen in the onboarding flow. You could call it the orbs/no orbs, whatever we are calling it screen
* https://sketch.cloud/s/YJ3xZ/v8WM2b1

#### Acceptance Criteria

* [ ] It should have a custom title
* [ ] The title should display the users name and gracefully fail without it.
* [ ] It should have a custom description.
* [ ] The text in the screenshot can be considered default values
* [ ] It should display a custom image

**Comment by redreceipt** [comment]
fwiw, this screen seems redundant now and just adds an extra, potentially confusing step.
