### ISSUE TITLE
[Onboarding] Build out API support

### ISSUE THREAD

**Issue by burkeshartsis** [ApollosProject/apollos-prototype#554]
## User Story

As a first time app user I want to personalize my app experience while learning exploring what is available to me so that I can grow spiritually in a purposeful and missional way.

#### Problem Details

We need a way to store either locally or through the API (both!?) all personal data from the onboarding experience. MVP can require a rock profile but this probably should function locally and sync with the api once a profile is created in the future. 
* https://sketch.cloud/s/YJ3xZ/JnoKgqM

#### Acceptance Criteria

* [ ] ???

**Comment by vinnyjth** [comment]
References #577
