### ISSUE TITLE
HMW: Expose the theme in an easier to use way?  Might just be documentation. Do we need to expose the whole theme? Right now things like card header color isn't exposed.

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#558]
- [ ] TODO: Host a lunch n' learn and produce initial documentation

**Comment by burkeshartsis** [comment]
https://varun.ca/styled-system/

**Comment by conrad-vanl** [comment]
This might overlap heavily with the work that Michael R. is doing on the design side, and is a pretty large task for what I see.
