### ISSUE TITLE
[Bug] Setting a user's location should update the user's location on the connect page

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-prototype#602]
As a user, when I update my location, I should see my newly selected location on the Connect screen. 

Right now I have to refresh my app to see the new location that I have selected.

**Comment by vinnyjth** [comment]
@redreceipt @cdanwards This might be an easier PR, either of you are welcome to take it if you have time this sprint.

**Comment by vinnyjth** [comment]
![2019-03-21 14 32 20](https://user-images.githubusercontent.com/1637694/54779835-30838e00-4be6-11e9-8e17-08ff2269b104.gif)

**Comment by redreceipt** [comment]
@vinnyjth yea I'll take a look

**Comment by redreceipt** [comment]
@vinnyjth do we manage this kinda stuff with state or some other local storage method?

**Comment by vinnyjth** [comment]
This is done. It was tested and working as of #640
