### ISSUE TITLE
Build ConnectedAboutYou component

### ISSUE THREAD

**Issue by burkeshartsis** [ApollosProject/apollos-prototype#609]
### User Story

As a first time app user I want to personalize my app experience while exploring what is available to me so that I can grow spiritually in a purposeful and missional way.

### Description
The current AboutYou component is not connected to GQL. We need to build a `ConnectedAboutYou` component and validate user input.

### Why
We need to validate user input to be API compliant and then save user inputs to their profile. 

### Acceptance Criteria
- [ ] It should validate user input to be API compliant.
- [ ] It should save user input via GQL.
- [ ] It should have test coverage 😉

### Possible Implementation & Open Questions
`ConnectedAboutYou` should follow the same paradigm we have used for `ConnectedContentCard` that basically just wraps `AboutYou` in a `Query` component. I would expect there might be some but very minimal API change to `AboutYou`. However, I think almost everything should be able to be handled with the current `OnPressPrimary` or `OnPressSecondary` props which accept functions that you can include slide advancement and form submission in. For now `ConnectedAboutYou` can live in the same directory as `AboutYou` and become the default export from that directory.

Additionally the form will need validation via `Formik`. You can reference [this PR](https://github.com/ApollosProject/apollos-prototype/pull/591/files#diff-6233f433e288ee3fa7f45f9a1db27aaa) for as a Formik example. Feel free to ask questions here to flush out your approach if needed.

### Other Resources

- [Design mockup/prototype](https://sketch.cloud/s/YJ3xZ/4aAWKrx)

**Comment by vinnyjth** [comment]
Related to #613
