### ISSUE TITLE
Build ConnectedAskName component

### ISSUE THREAD

**Issue by burkeshartsis** [ApollosProject/apollos-prototype#610]
### User Story

As a first time app user I want to personalize my app experience while exploring what is available to me so that I can grow spiritually in a purposeful and missional way.

### Description
The current AskName component is not connected to GQL. We need to build a `ConnectedAskName` component and validate the users input.

### Why
We need to validate user input to be API compliant and then save user inputs to their profile. 

### Acceptance Criteria
- [ ] It should validate user input to be API compliant.
- [ ] It should save user input via GQL.
- [ ] It should have test coverage 😉

### Possible Implementation & Open Questions
`ConnectedAskName` should follow the same paradigm we have used for `ConnectedContentCard` (and `ConnectedAboutYou`) that basically just wraps `AskName` in a `Query` component. I would expect there might be some but very minimal API change to `AskName`. However, I think almost everything should be able to be handled with the current `OnPressPrimary` or `OnPressSecondary` props which accept functions that you can include slide advancement and form submission in. For now `ConnectedAskName` can live in the same directory as `AskName` and become the default export from that directory.

Additionally the form inputs will need validation via `Formik`. You can reference [this PR](https://github.com/ApollosProject/apollos-prototype/pull/591/files#diff-6233f433e288ee3fa7f45f9a1db27aaa) for as a Formik example. Feel free to ask questions here to flush out your approach if needed.

### Other Resources

- [Design mockup/prototype](https://sketch.cloud/s/YJ3xZ/JnoKgqM)

**Comment by cdanwards** [comment]
@burkeshartsis For the `OnPressPrimary` call, do you have an example of passing scroll advancing or for submission by this?

**Comment by burkeshartsis** [comment]
[Here's](https://github.com/ApollosProject/apollos-prototype/blob/master/packages/apolloschurchapp/src/ui/Onboarding/index.js#L80) an example of passing in scroll advance @cdanwards. `onPressPrimary` just takes a function so whatever you give it will be called. Depending on where you do the form submission (at the connected component level or in the component itself) you would just want to make sure your submit function is called with whatever else that function is calling.
