### ISSUE TITLE
Check if form error states are working

### ISSUE THREAD

**Issue by burkeshartsis** [ApollosProject/apollos-prototype#614]
### Details

When working on #612 I noticed that I wasn't really able to trigger an error state. We should look into this.

### Expected Behavior

`TextInput` should have a red underline and if there is an error text provided it should be displayed. If we can get an accurate visual error state we should add tests for these to all places that use `TextInput`.

### Actual Behavior

Currently, there doesn't seem to be a change in `TextInput`'s visual state when an error is passed.

### Steps to Reproduce

1.  add an `errors` and `touched` object to one of the `AskName` stories
2. check that story in storybook for a visual error state.
3. additionally do the same thing on the `TextInput` stories directly.

**Comment by vinnyjth** [comment]
@burkeshartsis lol :D

**Comment by vinnyjth** [comment]
For future reference - @burkeshartsis and I forgot about this issue, and then later solved it in #640

**Comment by burkeshartsis** [comment]
LOL. For future future reference the error states **were** definitely broken. As @vinnyjth notes, they are fixed now.
