### ISSUE TITLE
[Personal Content] A user can view featured content on the home screen

### ISSUE THREAD

**Issue by IsaacHardy** [ApollosProject/apollos-prototype#616]
### User Story

As a User I want to view featured content so that I can know what is happening on my campus and relative to me.

### Description
We need to create a new big card with text for featured content on the top of the home feed 
### Why
This will allow churches to feature specific content or events 

### Acceptance Criteria

* [ ] It should [SPEC_DETAIL]

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by vinnyjth** [comment]
Done in #603
