### ISSUE TITLE
Further abstract hardcoded Apollos names and styles

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#617]
for iOS, we need to use splash screen pngs, not the xib file. this is for the CLI later. 
https://medium.com/@hellosunschein/launchimage-s-explained-33b88c02d027
https://github.com/crazycodeboy/react-native-splash-screen/tree/master/examples/ios/examples/Images.xcassets

for Android, we need to name the color something more generic than "deep water". also need to abstract the LauncherActivity name to @string/app_name.

I can start work on this ASAP as I would consider it a prerequisite for anyone making their own apps

cc @burkeshartsis

**Comment by vinnyjth** [comment]
@redreceipt Can you close this now?
