### ISSUE TITLE
Update iOS SDK Version

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-prototype#641]
AppCenter pushes to iTunesConnect aren't working because we are building on an old version of the iOS SDK. I'm assuming we can increment the SDK version with 0 drawbacks, but it's probably best we test it ;) 

![image (5)](https://user-images.githubusercontent.com/1637694/56291116-405d9780-60ea-11e9-880d-5bce35e5f65e.png)

**Comment by redreceipt** [comment]
@vinny I think that's an AppCenter problem. I did a customer support ticket for our old app about the same thing but they said they had it resolved. 😕

**Comment by redreceipt** [comment]
...actually I'm wrong, it's all configured inside AppCenter here

![Screen Shot 2019-04-18 at 1 34 19 PM](https://user-images.githubusercontent.com/2659478/56379992-015d3e00-61df-11e9-986a-98b60b1c5c86.png)

I changed to Xcode 10 and I'm re-running the build to see if that works.

**Comment by redreceipt** [comment]
Looks like we're good to go!

**Comment by vinnyjth** [comment]
You the man :D Thanks
