### ISSUE TITLE
Onboarding LocationFinder Crashes

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#648]
### Details

![Kapture 2019-04-18 at 16 20 47](https://user-images.githubusercontent.com/2659478/56388872-1a251e00-61f6-11e9-8c0d-7e49c4543892.gif)

Just going through onboarding on the simulator when you get to the location screen and click yes the app crashes so then I dismissed the warning and then have to reload the app and then it skips onboarding and when I go to look at my profile there's no information.

### Expected Behavior

Onboarding should work with no errors.

### Actual Behavior

Crashes at Location Finder

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by vinnyjth** [comment]
@redreceipt Can you try this again after rebuilding?

**Comment by redreceipt** [comment]
after the name screen, all these warnings popped up and there's no image

![Screen Shot 2019-04-24 at 10 15 20 AM](https://user-images.githubusercontent.com/2659478/56666465-f17ba900-6679-11e9-8bb4-5fd12e4fce8e.png)

**Comment by redreceipt** [comment]
and again after about you screen
![Screen Shot 2019-04-24 at 10 16 28 AM](https://user-images.githubusercontent.com/2659478/56666511-0eb07780-667a-11e9-86a2-716755bfc4c0.png)

**Comment by redreceipt** [comment]
and then it crashes again on locations

![Screen Shot 2019-04-24 at 10 16 50 AM](https://user-images.githubusercontent.com/2659478/56666535-1b34d000-667a-11e9-97d3-ff51e558febc.png)

**Comment by vinnyjth** [comment]
Was not able to reproduce at this time. Feel completely free to reopen if you are still getting this.
