### ISSUE TITLE
[Onboarding] DateInput should show default text, rather than default to `new Date()`

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-prototype#652]

**Comment by vinnyjth** [comment]
@conrad-vanl Might check in with Burke, but I believe this still needs to be done and is high priority. 

When you visit the "About Me" onboarding screen without a birthdate, you should see the default text rather than the current date in the datepicker field.

**Comment by burkeshartsis** [comment]
I'm actually working on this as we speak.

**Comment by burkeshartsis** [comment]
Related to this issue.

> "I almost missed that my birthday was wrong because the rest of the info about me was pre-filled and correct" – Caleb

@conrad-vanl how concerned with this are we. For location we force people to tap the button to "confirm" their location. We could do something similar here if we really wanted. I'm just not convinced it's the problem it's being made out to be and I'd almost rather let this be a concern of the user with less required interactions than force it.

**Comment by vinnyjth** [comment]
@burkeshartsis I believe @calebpanzas issue occured because the app showed his birthdate as today, rather than showing him the default text.

**Comment by burkeshartsis** [comment]
Oh I see. So this issue is the same! Alright got it. Should be fixed in my next commit.

**Comment by vinnyjth** [comment]
Fixed in #640
