### ISSUE TITLE
[Production Readiness] When Liking your _first_ ContentItem, the UI never updates to display that new content item.

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-prototype#672]
### Details

When Liking your _first_ ContentItem, the UI never updates to display that new content item.

### Expected Behavior

When liking your first content item you should see the item show up in the UI.

### Actual Behavior

You see nothing, until you refresh your app.

### Possible Fix

We are probably not mounting the required queries that are "updated" when liking ContentItems. We should probably make sure the container that loads Liked content items is mounted no matter what. 

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  Load the app with a logged in user.
2. Unlike all content items.
3. Refresh the app
4. Visit the connect tab
5. Like a content item
6. Visit the connect tab, you shouldn't see any liked content items.
7. Refresh the app.

### Stack Trace

</details>

**Comment by redreceipt** [comment]
Gif me please. Not sure what the issue is here. Here's my experience.

![Kapture 2019-05-15 at 9 56 20](https://user-images.githubusercontent.com/2659478/57781240-c70c9100-76f7-11e9-9735-ed003f4175cd.gif)

**Comment by redreceipt** [comment]
That also captures another bug, the "X" takes me back to Onboarding sometimes. If there's not an issue for that already I can make one.

**Comment by vinnyjth** [comment]
@redreceipt That is fixed in #698

**Comment by redreceipt** [comment]
gotcha, cool. well, I can't seem to reproduce the issue here, have any more details?

**Comment by vinnyjth** [comment]
@redreceipt Did you follow my steps to reproduce above?

**Comment by redreceipt** [comment]
By refresh, you just mean CMD+R?

**Comment by redreceipt** [comment]
ah, I see it now

**Comment by redreceipt** [comment]
ok so this may or may not be related but when liking something, this error comes out:

<img width="613" alt="Screen Shot 2019-05-15 at 1 12 12 PM" src="https://user-images.githubusercontent.com/2659478/57795139-3a6fcc00-7713-11e9-9a03-6a42b6adae64.png">

coming from this file

<img width="697" alt="Screen Shot 2019-05-15 at 1 13 45 PM" src="https://user-images.githubusercontent.com/2659478/57795179-55424080-7713-11e9-94b8-cc7181d5b631.png">

and this function

<img width="649" alt="Screen Shot 2019-05-15 at 1 13 51 PM" src="https://user-images.githubusercontent.com/2659478/57795194-5bd0b800-7713-11e9-90ca-ff7116622b4f.png">


using this query

<img width="449" alt="Screen Shot 2019-05-15 at 1 13 59 PM" src="https://user-images.githubusercontent.com/2659478/57795207-625f2f80-7713-11e9-885b-202c700b2e93.png">


isn't it odd that the `first: 3` call doesn't produce an error? I'm also thinking we just need to update some query cache to fix this bug and another related bug: #712

**Comment by redreceipt** [comment]
May also be related to #712
