### ISSUE TITLE
Rock Endpoints for Family, Home Group, and Serving Group Membership

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#676]
### User Story

As a user, I want to know if I'm in any groups so that I can do stuff with that info.

### Description

Add queries to `apollos-data-connector-rock` that tell me if I'm in any groups. ex.

`family(personID)`
`homeGroups(personID)`
`servingGroups(personID)`

### Why

For example, in our prayer feature, we don't want to show a list of community prayers if I'm not in any groups.

### Acceptance Criteria

* [ ] It should tell me if I'm in a family
* [ ] It should tell me if I'm in a home group
* [ ] It should tell me if I'm in a serving group
* [ ] (optional) It should give me an array of people in each of those groups

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by redreceipt** [comment]
cc @richarddubay

**Comment by redreceipt** [comment]
@vinnyjth you ok if I work on this? the AC would simply be adding a `Group` type and three queries that return an array of groups. Would add tremendous value for us right now and I'm confident the project as a whole in the future.

**Comment by vinnyjth** [comment]
@redreceipt Can you give me the 10 second update on what additions core would see from this? We might need to decide if this is something you guys work on in Newspring and then we move over to core eventually.

**Comment by redreceipt** [comment]
no client-side additions in core for now. I could do it on our API and then move it over but I was trying to avoid double work when it's almost guaranteed that core will have some `Group` implementation in the future. but also understand you don't wanto add scope to your plate. just thought the QA sprint might be a good opportunity

**Comment by redreceipt** [comment]
this first go around is simple: 

```
type Group {
  id
  leader Person
  members [Person]
}

Query {
  families(personID) [Group]
  homeGroups(personID) [Group]
  servingGroups(personID) [Group]
}

**Comment by vinnyjth** [comment]
Gotcha. I agree with you about it being important in core _eventually_. Not sure when that is though. Feel free to give this a stab, but I might not be able to set aside time to review it during this QA sprint.

**Comment by vinnyjth** [comment]
Done in #939
