### ISSUE TITLE
Android Splash Images Not Being Used

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#677]
### Details

In `styles.xml` Android is pointing to `background_splash` files but they are called `screen` in the file structure so that line and those background image files aren't doing anything.

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by vinnyjth** [comment]
Fixed at some point.
