### ISSUE TITLE
[On-Boarding] Text to Login Error

### ISSUE THREAD

**Issue by calebpanza** [ApollosProject/apollos-prototype#682]
### Details

The bug comes in the way that the text to login works, or rather doesn't work right now. There is a hack that allows you to get past the login screen, but it's not working as expected.

### Expected Behavior

When on the on-boarding screen that asks you to enter in your phone number, I should be able to enter in my phone number, enter the confirmation code, and navigate to the app's home page.

### Actual Behavior

When on the on-boarding screen that asks you to enter in your phone number, I enter in my phone number and get an error that asks me to check my phone number. Within the next 30-60 seconds, the confirmation code will still come through as expected. I just am unable to get past the "enter your phone number" screen, and so I have no way to enter in the confirmation code.

If I close the app, reopen it, and go through the entire process again (getting a new confirmation code in the process), it will let me through at that point.

<details><summary>Additional Info</summary>

### Your Environment

- iPhone Xs (gold. lol)
- iOS 12.2

### Steps to Reproduce

1.  Open the app without having logged in
2. Enter in your phone number
3. Receive an error asking you to enter it in again with no way of getting past the login screen
4. *** see description above for hack to get through ***

</details>

**Comment by vinnyjth** [comment]
This is a great issue. Really thankful for your description and steps to reproduce. Can you please send me the phone number you are trying to use to login? Please include all `(` and `-` and ` ` characters :)

**Comment by calebpanza** [comment]
I this is exactly what I typed in: 9088943822 (I did not include and special characters)

Thanks
Caleb

**Comment by conrad-vanl** [comment]
I removed @calebpanza's phone number from this comment chain since it's public. If he doesn't care, you can repost, but I have it and can send it to whoever needs it :)

**Comment by calebpanza** [comment]
😂😂😂 didn’t even think that one through at all. Thanks for the catch!

Thanks
Caleb

**Comment by vinnyjth** [comment]
My bad too! I didn't think that through at all, I should have asked for you to replace your numbers with 9s or something

**Comment by vinnyjth** [comment]
This was caused by Heroku sleeping
