### ISSUE TITLE
Schema Design: People

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#7]
## Acceptance Criteria

- [ ] Model Rock's core people schema in graphql. Lets start with the basics - first name, last name, nick name, brith date, email. Associations (like campus or groups) can come later
- [ ] Can get a person by ID using the Node query
- [ ] Can query for users by email

**Comment by IsaacHardy** [comment]
@conrad-vanl Looking for acceptance criteria for this issue. Trying to determine the scope of this schema and home much of it should be saved for the authentication schema.

**Comment by conrad-vanl** [comment]
@IsaacHardy done
