### ISSUE TITLE
Photos Aren't Working for Other People's Profiles

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#702]
### Details

When querying for `currentUser` the profile photo URL shows up fine:

<img width="1413" alt="Screen Shot 2019-05-13 at 11 23 39 AM" src="https://user-images.githubusercontent.com/2659478/57633613-ccd86a00-7571-11e9-8c3c-8efc6ca48cf9.png">

But when getting a `Person` by other means, all information except the photo URL shows up:

<img width="1213" alt="Screen Shot 2019-05-13 at 11 23 47 AM" src="https://user-images.githubusercontent.com/2659478/57633734-f396a080-7571-11e9-8eaf-42264419d371.png">

The query that we're running is using the `Person` data source functions from `apollo-dataconnector-rock`

<img width="677" alt="Screen Shot 2019-05-13 at 11 24 15 AM" src="https://user-images.githubusercontent.com/2659478/57633781-11fc9c00-7572-11e9-92eb-e45dc916907d.png">

### Expected Behavior

Photo URLs should show up

### Actual Behavior

They don't.

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by vinnyjth** [comment]
We fixed this in an unreleased version. You'll be able to do this after pulling in this release
https://github.com/ApollosProject/apollos-prototype/commit/1f04d21f81ee7e99199629a70fd739feea27643a

**Comment by richarddubay** [comment]
@vinnyjth "Unreleased version"? Does that mean the next time we get a version we'll get it? I did hear that we were skipping a version and going to the next one, but I don't know when that's supposed to happen.
