### ISSUE TITLE
[Willow/UI-Kit] Create Youtube Player for Demoing

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-prototype#704]
### User Story

As a church decision maker, I should be able to demo both a native approach and a youtube approach to a video player, in order to make an educated choice about what player I should use in my app.

### Description
We need to demo a Youtube video player for Willow, that we would eventually want to implement in place of our native MediaPlayer if Willow decided the trade offs were not worth transferring their media content to a non-youtube host. 

Here's a URL for a youtube video useful for testing: https://youtu.be/48VQrC06m-Y

### Acceptance Criteria

* [ ] It should have a story in UI-kit that demos the Youtube player in a context similar to the existing media player.
* [ ] Support pausing, playing, and stopping a video.
* [ ] (Stretch goal) support the same lock screen controls / audio support as the existing player

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by burkeshartsis** [comment]
I think we can rule this out based on pods and the privacy violation on youtube. 

https://github.com/inProgress-team/react-native-youtube

**Comment by burkeshartsis** [comment]
We'll just have to roll something based on the yt player api

https://developers.google.com/youtube/iframe_api_reference

**Comment by vinnyjth** [comment]
I don't know if this changes anything, but I think you can use that `lib` without the standalone iOS player.

**Comment by burkeshartsis** [comment]
@vinnyjth having looked at that package closer I'm just not sure it's worth it anymore. Given that the "native ios library" underneath just opens a webview it seems redundant to use the library in the first place. It probably provides a more first class Android experience though but it notes that the Youtube app has to be installed as well so there is a surprised dependency on that (even if it basically comes preinstalled on virtually every android phone it is possible to be removed or not bundled on some devices). That lib also has some unconventional setup procedures that might not be acceptable for a project like ours.

TBH, I just want to build something at this point. Truthfully, I'm happy to go in whatever direction you want.

**Comment by vinnyjth** [comment]
@burkeshartsis Feel free to go whatever direction you're most comfortable with. We really just need to demo the caveats of Youtube clearly, so I'm fine with whatever direction you take to get there.

**Comment by burkeshartsis** [comment]
@vinnyjth can this be closed?
