### ISSUE TITLE
Fix Avatar Margin on Profile

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#718]
### Details

When we removed the margins from the Avatar we forgot to go back and adjust the margin on the profile page.

<img width="403" alt="Screen Shot 2019-05-15 at 9 51 26 AM" src="https://user-images.githubusercontent.com/2659478/57780910-2ddd7a80-76f7-11e9-96f1-c168a67756a3.png">

### Expected Behavior

A little space between avatar and check-in

### Actual Behavior

No space.

### Possible Fix

Add a view around the avatar and give it some `marginBottom`.

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by redreceipt** [comment]
@vinnyjth good if I fix this?

**Comment by vinnyjth** [comment]
@redreceipt Totally!
