### ISSUE TITLE
Media player minimized view styling issues

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#726]
### Details

See screenshot: 

![IMG_3954](https://user-images.githubusercontent.com/103927/57856291-56767a80-77b2-11e9-86bc-678d31bbcd4f.jpeg)

### Expected Behavior

- [ ] too much spacing above the player
- [ ] long text doesn't truncate over the pause button

### Possible Fix

The spacing issue can be tweaked in the [Spacer component](https://github.com/ApollosProject/apollos-prototype/blob/master/packages/apolloschurchapp/src/ui/MediaPlayer/MediaPlayerSpacer.js)

The truncated text in the [MiniControls](https://github.com/ApollosProject/apollos-prototype/blob/master/packages/apolloschurchapp/src/ui/MediaPlayer/MiniControls.js#L160-L163)

<details><summary>Additional Info</summary>

### Your Environment

- NewSpring iOS App

### Steps to Reproduce

1.  Navigate to any sermon or content item with a video
2. Play video
3. Minimize player

</details>

**Comment by vinnyjth** [comment]
Part one is fixed in #543

**Comment by vinnyjth** [comment]
Fixed in the PR that closed #952

**Comment by vinnyjth** [comment]
References PR #982
