### ISSUE TITLE
How to handle duplicate phone numbers

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#746]
### Details

I'm logging this as a bug although it might be considered an enhancement. Essentially NewSpring brought to our attention an issue with duplicate phone numbers. Example:

Frank's son is in Rock, but is associated with Frank's phone number. This is common for churches when you check a kid into childcare, for example.
When Frank signed into the app using sms login, it logged him in as his son.

HMW correct?

One solution might be that whenever there's more than one account associated with a phone number, that we create a new account.

**Comment by calebpanza** [comment]
So in looking through Rock's API and our Db, it looks like there are two relevant tables for this: `People` and `UserLogins` in which `People` contain a collection of `UserLogins`

People is where we run the risk of having a ton of duplicate records in Rock, so my question would be this: can we create a new account (in `UserLogins`) using just the phone number and passcode and not associate that account with a person (in `People`) until we have additional data points (First Name, Last Name, etc.)???

**Comment by FrankGrand** [comment]
The more I think through this, it feels like we need an added logic step to the login process.
1. Person enters phone number to login, verify the code sent by Twilio
2. Check to see if someone already has a User Account (the `UserLogin` table)...if so, that is the person
3. If no account exists for that phone number, create a new user

This will increase the amount of duplicates, but we do have a process that should connect the dots within 24-48 hrs.

If we don't somehow look at the User Account, there doesn't seem to be a way to ever solve the problem of people who 'share' a phone number
