### ISSUE TITLE
[Onboarding] User's with a campus should have the option to continue

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-prototype#767]
### User Story

As a user who has granted location permissions and has a campus, I should see a "Continue" button, and my campus, when visiting the LocationFinder screen. 

As a user who has **not** granted location permissions and has a campus, I should see "Select a Campus" and a skip button.

As a user who has **not** granted location permission, and does **not** have a campus, I should see "Select a Campus" and a skip button. 

As a user who has granted location permission, and does **not** have a campus, I should see "Select a Campus" and a skip button. 

### Acceptance Criteria

Support the following scenarios. 

* [ ] User with Campus and with Location Permissions
* [x] User without Campus and with Location Permissions - this scenario is supported
* [ ] User with Campus and without Location Permissions
* [x] User without Campus and without Location Permissions - this scenario is supported

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by redreceipt** [comment]
🙌 I can't wait to fix this

**Comment by redreceipt** [comment]
need to fix https://github.com/ApollosProject/apollos-prototype/issues/771 first. https://github.com/ApollosProject/apollos-prototype/pull/772 didn't do it.

![20190619_163330](https://user-images.githubusercontent.com/2659478/59798455-2db13b80-92b0-11e9-97d0-3d785cf8ddcf.gif)

I see this was deprecated above, still want me to work on this @vinnyjth?

**Comment by redreceipt** [comment]
blocked: https://github.com/ApollosProject/apollos-prototype/issues/814

**Comment by vinnyjth** [comment]
I believe we resolved this to a preferred state in #891
