### ISSUE TITLE
LocationFinder Map blank

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#768]
### Details

I downloaded and was logging into the new build for the first time, when I went through onboarding and got to the location finder, Google Maps was blank.

![Screenshot_20190605-162031](https://user-images.githubusercontent.com/2659478/58987823-5adcf480-87ae-11e9-8317-29ee93e2baf5.png)

### Expected Behavior

Should see a map

### Actual Behavior

Saw blank beige screen 

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile): Android 10, Pixel 3
- Link to your project:

### Steps to Reproduce

1.  logout
2. go through onboarding
3. select campus
4.

### Stack Trace

</details>

**Comment by vinnyjth** [comment]
@redreceipt This should be fixed, give it another shot on your device when the _real_  build gets to your phone.

**Comment by redreceipt** [comment]
yea can't reproduce
