### ISSUE TITLE
Update GraphQL to Apollo Standards

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#769]
### User Story

As a developer, I want to write GraphQL client that is inline with Apollo best practices.

<img width="752" alt="query" src="https://user-images.githubusercontent.com/2659478/59043614-8b726c00-884a-11e9-8528-84006d231dcb.png">

### Description

Capitalizes query names to `ALL_CAPS` convention.

### Why

We should be sticking to community conventions.

### Acceptance Criteria

* [ ] It should [SPEC_DETAIL]

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by redreceipt** [comment]
@vinnyjth did your merge close this one?

**Comment by vinnyjth** [comment]
Yep! in #789
