### ISSUE TITLE
LocationFinder crashes Android

### ISSUE THREAD

**Issue by cdanwards** [ApollosProject/apollos-prototype#771]
### Apollos Version: x.x.x

1.0.0-beta.0

### Details

When navigating through either the locationfinder in onboarding or navigating to the locations section under user-settings, there's an unhandled error and the app crashes.

### Expected Behavior

The mapview should load with a list of campuses.

### Actual Behavior

The app crashes.

### Possible Fix

There's an initial load, then the app pulls up campuses and quickly crashes. Maybe there's something with that query call? It just started happening recently.

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4): Android SDK 28
- Operating System and version (desktop or mobile): Mobile
- Link to your project:

### Steps to Reproduce

![Android-LocationFinder-Crash](https://user-images.githubusercontent.com/8878532/59216052-cd701a80-8b88-11e9-93a8-9b8fd1bc57b4.gif)

### Stack Trace

Very little visibility on this.

</details>

**Comment by cdanwards** [comment]
We're having this in the NewSpring Apollos Project and will leave any info I find.

**Comment by vinnyjth** [comment]
Fixed in #772
