### ISSUE TITLE
Update ConnectedComponents to accept a component prop

### ISSUE THREAD

**Issue by burkeshartsis** [ApollosProject/apollos-prototype#774]
### User Story

As an engineer I want to be able to swap out a ConnectedComponents rendered "child" so that I can reuse ConnectedComponents in the same way we can regular Components.

### Why
Our coding architecture encourages simple modular pure components that can be reused that are "driven by a ConnectedComponent. Currently connected components are hardcoded and tied to render their pure "child" component that they fetch data for. This makes it impossible to reuse them or customize the rendered child while keeping the ConnectedComponent unchanged resulting in unnecessary copy/paste and code debt. 

### Acceptance Criteria
Decouple ConnectedComponents from their rendered children.

### Possible Implementation & Open Questions
- add a `component` prop to ConnectedComponents
- default `component` to the current rendered "child"

**Comment by burkeshartsis** [comment]
@vinnyjth I didn't close this because I was going to refactor the ui auth components as well and figured that PR would close this issue too.

**Comment by vinnyjth** [comment]
We should create a new issue for that push to Modularize Auth or piggyback of this issue 

https://github.com/ApollosProject/apollos-prototype/issues/777

**Comment by vinnyjth** [comment]
https://github.com/ApollosProject/apollos-prototype/issues/785

**Comment by burkeshartsis** [comment]
That works for me!
