### ISSUE TITLE
[Auth] Mobile Number and SMS Token should AutoFocus and open Keyboard when the screen is rendered

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-prototype#778]
### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by burkeshartsis** [comment]
Can someone confirm this doesn't already work? This happens in both my iOS and Android sims.

**Comment by burkeshartsis** [comment]
@vinnyjth you created this issue. Do you mind checking if this is still an issue?

**Comment by vinnyjth** [comment]
@burkeshartsis Michael mentioned this was an issue. I haven't confirmed or denied it's existence, so we can close it for now.
