### ISSUE TITLE
Determine ability to track live stream schedule or status

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#78]
High-level goal of this issue is to determine how we're going to integrate with ChOP live status, and create a graphql schema for it.

## User Story

We only want to display the "We're live" banner when the church is actually broadcasting a live event

#### Problem Details

* There might be a Church Online api that allows us to get live events or streaming status
    * If not, lets sync with the Life Church people on next steps here, as it was suggested this is something they'd be willing to build. At this point, we can explore other potential alternative points of integration as well (can we integrate directly with Rock to get a worship schedule, for example)
    * If so, lets understand what the API provides and how it structures information
* Lets consider how we want to integrate with such an API...we can either ping the API ever so often to see if the church is currently live, or if the API exposes a schedule, we can use that schedule to statically determine if the church _should be_ live or not

#### Acceptance Criteria

* [ ] Create a graphql schema for querying live status and the streaming URL. We do **NOT** need to hook this query up to the ChOP API though, this issue is just for understanding their API and spec'ing out what schema we want to use
* [ ] Write a resolver for above query that returns fake data
* [ ] Hook our "Live Now" button up to this data
* [ ] Document and create issues for next steps on ChOP integration

**Comment by richarddubay** [comment]
@conrad-vanl So I did some research on this, trying to find a Church Online Platform API, but I didn't really find anything. Life.Church does have a repo, but it's super old and there is no documentation or edits (https://github.com/lifechurch/churchonlineplatform-api). The lack of an API could be why we ended up just creating the thing in EE that we use for determining our live status.

**Comment by conrad-vanl** [comment]
Then we should reach out to David Fedor over at Life.Church and see what the best path forward for integration will be
