### ISSUE TITLE
[Connect] Connect Action Button  

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-prototype#782]
![image](https://user-images.githubusercontent.com/1637694/59365679-f3232e00-8d06-11e9-842d-f9f155d740b2.png)
![image](https://user-images.githubusercontent.com/1637694/59365840-41383180-8d07-11e9-8833-fa19c56a976b.png)

### User Story

As a `<type of user>` _(who)_ I want to `<perform an action>` _(what)_ so that I can `<achieve a goal>` _(why)_.

### Acceptance Criteria

* [ ] Should support **N** actions
* [ ] Render with an `onPress`, `label`, and `icon`

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by IsaacHardy** [comment]
+1

**Comment by vinnyjth** [comment]
Fixed! at some point...
