### ISSUE TITLE
Create PushPay account and determine initial integration point

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#79]
## User Story

As a user I want to give to push pay through the app

#### Problem Details _(Optional)_

* Create a PushPay account and an "Apollos Church" giving page on PushPay
* Take a peak at the PushPay developer and API docs to see if there's any potential for future integration. If so, document thoughts

#### Acceptance Criteria _(Optional)_

* [ ] If this issue is done after #80, then link the giving link on the connect menu to open the PushPay giving screen

**Comment by cdanwards** [comment]
@conrad-vanl are we wanting to use the echurch solution presented by pushpay?

**Comment by conrad-vanl** [comment]
@cdanwards that appears to be a competing product to Apollos, so I dont believe so. The API docs I was referencing above are here - https://pushpay.io/docs/introduction

Basically, this issue entails creating a normal PushPay account as a church (if we can) and determining the best way we can achieve the user story of giving from the app. The MVP for this is likely just linking out to pushpay's mobile giving site (example: https://pushpay.com/g/watermark?src=hpp) but perhaps there are other integrations we can consider. For example: supporting a simple give form in the app where a user can select a fund and the amount they want to give, then just filling out their credit card info on the website. Basically: understand what could be possible with PushPay's API. The other stories to consider would be around "how much have I given this year" or otherwise having visibility on your history.

**Comment by cdanwards** [comment]
@conrad-vanl so, I'm not sure that we're able to get a pushpay instance without it being a paid account. But, I was able to verify that we would have the capability with their API to make calls for funds, anticipated payments, etc.

Payments: https://pushpay.io/docs/operations/payments#post__v1_anticipatedpayments
Past Payments: https://pushpay.io/docs/operations/payments#get__v1_my_payments
Funds: https://pushpay.io/docs/operations/funds#get__v1_merchant_merchantKey_funds

**Comment by conrad-vanl** [comment]
Maybe we should reach out to Rob (on our weekly standup calls) about how we should get in touch with PushPay to get some sort of sandbox account set up for us? He mentioned having a good relationship with them. What would be your thoughts there?

**Comment by cdanwards** [comment]
@conrad-vanl I think that's a good step forward. Going that route as apposed to speaking to an account manager or something, which they require you to do even for a quote, would be more productive I think.

**Comment by conrad-vanl** [comment]
@cdanwards you up to follow up with Rob on this? I can probably track down contact info if so.

**Comment by cdanwards** [comment]
@conrad-vanl definitely!

**Comment by conrad-vanl** [comment]
Hey @cdanwards what's the status on this one?

**Comment by cdanwards** [comment]
@conrad-vanl I may have missed it, but I didn't receive his contact info. I will today for sure.

**Comment by cdanwards** [comment]
@conrad-vanl I messaged Rob about the PushPay sandbox account. I imagine he'll mention it tomorrow in the stand-up call

**Comment by cdanwards** [comment]
Rob is reaching out to PushPay about a sandbox account! @conrad-vanl

**Comment by conrad-vanl** [comment]
@cdanwards did we ever hear back from Rob or the PushPay folks on this?
