### ISSUE TITLE
[Android] Videos cause the app to crash

### ISSUE THREAD

**Issue by cdanwards** [ApollosProject/apollos-prototype#790]
### Apollos Version: 

v1.0.0-beta.0

### Details

Whenever a video is launched, it begins to load the video but after a second the whole app crashes.

### Expected Behavior

The video should load and play.

### Actual Behavior

The app crashes

### Possible Fix

For us, this happened after the upgrade to RN 59. Not sure if there's something there.

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

![20190605_204729](https://user-images.githubusercontent.com/8878532/59569744-ddda3680-905b-11e9-85d8-a8e30c0afb55.gif)

### Stack Trace

No visibility on this at all.

</details>

**Comment by vinnyjth** [comment]
Thanks for reporting this @cdanwards. Is this happening only on your app or are you seeing this on core as well?

**Comment by cdanwards** [comment]
@vinnyjth I'm seeing this on Core as well. I tested it on the beta app on @redreceipt physical device.

**Comment by vinnyjth** [comment]
@cdanwards Can you send me the OS version and device model for the devices you are seeing the crash on? This is something we saw locally at some point, but definitely fixed.

**Comment by cdanwards** [comment]
@vinnyjth His phone is a Pixel 3 with OS 10. My sim is a Pixel 2 XL API 28 (I'm honestly not super familiar with android versioning). Michael said he does have the latest apollos prototype on there as well.
