### ISSUE TITLE
Can't Close Checkin Screen

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#792]
### Details

The close button on the check-in screen doesn't work.

### Expected Behavior

Should close and go back to the connect tab.

### Actual Behavior

Does nothing

![Kapture 2019-06-17 at 8 27 26](https://user-images.githubusercontent.com/2659478/59604340-ecffc980-90d9-11e9-975d-f488a61e4504.gif)

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by vinnyjth** [comment]
Good catch!
