### ISSUE TITLE
Add to Apple Wallet Broken

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#795]
### Details

Can't add the check-in barcode to Apple Wallet, just spins.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2659478/59615641-dadd5580-90f0-11e9-8232-1f42960027b2.gif)

### Expected Behavior

Should add the barcode to the Apple Wallet.

### Actual Behavior

The icon just spins and doesn't do anything.

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by redreceipt** [comment]
@conrad-vanl I know I've seen you do this in a demo before, any idea why this might be broken?

**Comment by vinnyjth** [comment]
🤔 I can look at this
