### ISSUE TITLE
[Use] URL Slug code that NS developed in core

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-prototype#796]
### User Story

As a user, I should get links to content on the web when I share content in the app.

### Description
Newspring developed a strategy for integrating the slugs + content channels in Rock to create a Permalink. We should consult @richarddubay and port this functionality to Core . 

### Acceptance Criteria

* [ ] It should [SPEC_DETAIL]

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by vinnyjth** [comment]
@redreceipt  Porting this to core would be much appreciated

**Comment by redreceipt** [comment]
Lucky for us @cdanwards had been working in this for two weeks! I'm pretty sure he's already done what this issue calls for. 

We don't need it to deep link yet right? Just for the API to spit out the web link?

**Comment by richarddubay** [comment]
@vinnyjth @redreceipt If you're just looking to get the link, you can just checkout what we did for sharing the URL. Something like: https://github.com/NewSpring/ApollosProject/blob/develop/packages/apollos-church-api/src/data/content-items/data-source.js#L146

**Comment by redreceipt** [comment]
oh perfect, I'll drop it in

**Comment by redreceipt** [comment]
@richarddubay is there a reason Newspring is using a custom attr `ChannelUrl`? There's already a built-in attr called `ItemUrl` on the content channels and from what I can tell, that's its purpose.

**Comment by richarddubay** [comment]
Looking at this (https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Client/CodeGenerated/ContentChannel.cs) it looks like both `ItemUrl` and `ChannelUrl` are core items. If you look here (https://apollosrock.newspring.cc/page/340) it shows `ChannelUrl` in the grid, but what I don't know (yet) is why it doesn't show up as an option to set when I edit one of the content channels there. 

Either way, I don't think `ChannelUrl` is custom.

**Comment by redreceipt** [comment]
gotcha, I'm gonna switch core's to `itemUrl` reading the helper description it looks like it's what we want. Do you agree?

<img width="1148" alt="Screen Shot 2019-08-09 at 2 28 42 PM" src="https://user-images.githubusercontent.com/2659478/62800722-132a6000-bab2-11e9-969b-1b65295fd0ff.png">

**Comment by richarddubay** [comment]
@redreceipt If that works, that's cool. Whatever works in `apollosrock`. That helper text says "Lava template" so ... as long as they doesn't actually _need_ a lava template. 😂
