### ISSUE TITLE
Create reusable `WebView` route

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#80]
## User Story

We want to be able to direct the user to web content.

#### Problem Details _(Optional)_

* Sometimes, we will link to web content as core features - such as for live streaming or within the connect menu.
* Other times it's used very generically, like on links within Content or in a push notification

#### Acceptance Criteria _(Optional)_

* [ ] Simple api to use, like `navigation.push('WebView', { uri: 'https://google.com' })`
* [ ] Hook up atleast one of the links on the connect menu to open webview
* [ ] If this issue done after #79, hook up the giving button in the connect menu to open webview
* [ ] Replace `LiveModal` with this webview modal

**Comment by cdanwards** [comment]
@conrad-vanl After looking into Push Pay, for churches they have the echurch.com platform. I've not used this service before so I'm unsure if that's the desired solution.
