### ISSUE TITLE
Onboarding Slide 2 Should Show First Name

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#807]
### User Story

As a user, I want to see my first name on onboarding screen 2.

### Description

Currently, the first name is populated only if the data is pulled from Rock, not if the user just wrote it in on the screen before. So we probably just need to update the cached query.

![Kapture 2019-06-19 at 14 44 42](https://user-images.githubusercontent.com/2659478/59791876-0737d400-92a1-11e9-9eaf-f9a5909b5f9e.gif)

### Why

it's a better experience

### Acceptance Criteria

* [ ] It should always show the first name if there's one given.

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by vinnyjth** [comment]
@redreceipt This was working per v1 of Onboarding. So this is definitely a bug.

**Comment by vinnyjth** [comment]
![2019-06-20 08 13 20](https://user-images.githubusercontent.com/1637694/59848489-49a9f100-9333-11e9-9a21-4ab789fe8e11.gif)

**Comment by vinnyjth** [comment]
Can you send me any details on how to reproduce?

**Comment by redreceipt** [comment]
Make sure that you don’t have a first name in Rock when you start the process

—
Michael

**Comment by vinnyjth** [comment]
@redreceipt Fixed by merging #787 (look at the first half of this gif)

![2019-06-26 07 54 05](https://user-images.githubusercontent.com/1637694/60178535-bfa5d080-97e9-11e9-8b5d-66bd77933db8.gif)
