### ISSUE TITLE
Check-In Image Not Loading

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#811]
### Details

The image from check-in pass never loads on Android, a little context, I had a duplicate account on Rock that was recently merged.

### Expected Behavior

Image should load

### Actual Behavior

Image never loads so I can't exit out because I can't see the modal header.

![Kapture 2019-06-20 at 10 57 42](https://user-images.githubusercontent.com/2659478/59859619-0ce9f400-934b-11e9-9a62-a83aa0dc96b5.gif)

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by vinnyjth** [comment]
I am currently unable to reproduce this issue naturally, but I can recreate the big gray box by setting the `isLoading` on the `Thumbnail`  in the pass to true. We should fix this by making sure the the placeholder image doesn't take up 100% of the space.

**Comment by redreceipt** [comment]
this is why it's breaking, the thumbnail uri is coming in like this 

<img width="653" alt="Screen Shot 2019-06-26 at 3 46 59 PM" src="https://user-images.githubusercontent.com/2659478/60209960-c48a7480-9829-11e9-9612-38fc31f6e3dc.png">

investigating now...

**Comment by redreceipt** [comment]
so there's two issues here:
1. why is the uri not complete for me?
2. the gray box shouldn't be so big for the thumbnail placeholder, which is a `ui-kit/ConnectedImage`. that file is very scary...

**Comment by redreceipt** [comment]
fixed the gray box thing
