### ISSUE TITLE
[UI] Home Tab - iPad UI Broken Card

### ISSUE THREAD

**Issue by calebpanza** [ApollosProject/apollos-prototype#845]
### Details
When visiting the **home tab** in the Apollos App on an iPad, most of the cards look correct, but some of them are overlapping and breaking incorrectly 

### Expected Behavior
The cards should render exactly as they do on a mobile device: a single feed of cards stacked on top of one another

### Actual Behavior
The cards render in a single feed, and then (seemingly at random) one or more cards will not break into a new line, but rather overlap next to each other.

### Possible Fix
It looks like it could be related to the cards when they are in a state that does not have include an image.

<details><summary>Additional Info</summary>

### Your Environment

- iOS 12.2 Simulator
- iPad Pro (12.9") Simulator

### Steps to Reproduce
Run the project with any iPad Simulator
![Screen Shot 2019-07-03 at 2 53 25 PM](https://user-images.githubusercontent.com/45076058/60814327-6af84300-a163-11e9-9ce3-3e4dce1dd5f1.png)

</details>

**Comment by calebpanza** [comment]
@vinnyjth when do you think this will be ready (roughly). We are planning out presentations and I just want to know if we should prepare to show iPad views in that or not.

**Comment by burkeshartsis** [comment]
@calebpanza do you mind checking the latest build on master. I'm not able to reproduce this any more. If you see it still broken can you screenshot it for me too!
