### ISSUE TITLE
[UI] Discover Tab - iPad UI Broken Cards

### ISSUE THREAD

**Issue by calebpanza** [ApollosProject/apollos-prototype#846]
### Details
When viewing the Discover Tab on an iPad sized device, the cards overlap one another in a way that makes the tab unusable and indistinguishable

### Expected Behavior
The cards in the Discover tab should line up a horizontal card feed exactly like they do on a mobile phone

### Actual Behavior
Cards are essentially being sliced in half and have labels in between them

### Possible Fix
The cards may have a fixed max-width set on them

<details><summary>Additional Info</summary>

### Your Environment

- iOS 12.2 Simulator
- iPad Pro (12.9") Simulator

### Steps to Reproduce
Run the app in any iPad simulator
![Screen Shot 2019-07-03 at 2 53 33 PM](https://user-images.githubusercontent.com/45076058/60814706-202afb00-a164-11e9-8109-aa608ca585c5.png)

</details>

**Comment by calebpanza** [comment]
@vinnyjth when do you think this will be ready (roughly). We are planning out presentations and I just want to know if we should prepare to show iPad views in that or not.

**Comment by vinnyjth** [comment]
@conrad-vanl or @burkeshartsis may have a better idea of their availability to work on this issue
