### ISSUE TITLE
[UI] FeaturedCard and HighlightCard

### ISSUE THREAD

**Issue by burkeshartsis** [ApollosProject/apollos-prototype#851]
### User Story

As a user I want to experience a "Live" sermon experience that combines sermon information with the livestream.

### Description
This is a `FeaturedCard` and `HighlightCard` to be displayed in the home feed. These cards are visually distinctive from other cards/content in the feed used to highlight their rich media content. 

![image](https://user-images.githubusercontent.com/2053547/60890918-4b781d80-a22a-11e9-8b05-35ebe4c138cf.png)

### Acceptance Criteria
- [ ] It should gracefully handle it's props in a way that if one was missing it might still function.
- [ ] It should accept custom title, description, and label text.
- [ ] The label should accept a custom background color but default to brand or transparent coloring.
- [ ] It should accept a custom gradient color and default to brand coloring.
- [ ] It should display if it has been liked or not
- [ ] It should accept media icon and default to "play"

### Other Resources

- [Basecamp todo](https://3.basecamp.com/3926363/buckets/6947926/todos/1898958850)

**Comment by michael-riddering** [comment]
`ContentCard` never exceeds the height of the tallest Featured Card (in the case of an XR, that is 528px)

<img width="864" alt="Screen Shot 2019-07-10 at 7 38 40 AM" src="https://user-images.githubusercontent.com/41083408/60974245-fc43f280-a2e6-11e9-903d-0ce50187cf89.png">
