### ISSUE TITLE
Show content children on content screens

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#89]
## User Story

As a user I want to browse a series' sermons, or a studies' devotionals

#### Problem Details _(Optional)_

* Implement the horizontal scroller from NS/Apollos to navigate to a content's child items

![image](https://user-images.githubusercontent.com/103927/41607852-a0d56100-73ac-11e8-8067-d33829ee629d.png)

#### Acceptance Criteria _(Optional)_

* [ ] It should show a horizontal scroller that links to individual child items
* [ ] Should only show a horizontal scroller if that item has children

**Comment by richarddubay** [comment]
Do you feel like this task and #91 would use different horizontal scrollers? Same scroller with different props? They feel like two different scrollers, but I thought I'd ask.
