### ISSUE TITLE
As a user, I should be signed out of the client if I receive an authentication error. 

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-prototype#890]
### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by vinnyjth** [comment]
@redreceipt This is a fun one to tackle, if you are looking for interesting problems to solve. I can catch you up on potential solutions.

**Comment by redreceipt** [comment]
I'm available to video chat all day if you wanna give me the summary

**Comment by vinnyjth** [comment]
Closed in #927
