### ISSUE TITLE
Create horizontal scrollers on engage screen

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#91]
## User Story

As a user I want to browse a few of the top content items in each channel

#### Problem Details _(Optional)_

![image.png](https://images.zenhubusercontent.com/55bcf69f4f7a08fbb7f4086a/dfa7323b-d8ed-4b90-b855-6c3b3b02dc98)

#### Acceptance Criteria _(Optional)_

* [ ] It should create a reusable horizontal feed/scroller type component
* [ ] MVP can utilize the same type of card for all content channels (the horizontal card with the photo on the left and title on the right). This works similarly to new App Store app on iOS

**Comment by IsaacHardy** [comment]
@conrad-vanl @burkeshartsis Will this reusable component behave like a component in our `UI` directory?

**Comment by IsaacHardy** [comment]
@conrad-vanl I'm also a bit confused about the second point of the acceptance criteria. In the mock, I see a square image that is centered with text, but in the AC you are suggesting **(the horizontal card with the photo on the left and title on the right)**

**Comment by burkeshartsis** [comment]
Hey @IsaacHardy the horizontal feed/scroller would likely be a reusable component in `/ui` much like `FeedView` is now.

I agree these is some ambiguity on which card lives in the scroller for what content. It seems like @conrad-vanl is just suggesting to simplify things for now and use the card that shows a title as it would work for all content types. I'm happy to meet with you tomorrow and talk to you about this more.
