### ISSUE TITLE
Onboarding Button Styles

### ISSUE THREAD

**Issue by cdanwards** [ApollosProject/apollos-prototype#914]
### Details

The button to advance onboarding screens needs some work on smaller devices: 

![Screenshot_20190605-202134](https://user-images.githubusercontent.com/8878532/61740683-40aaa600-ad5d-11e9-99e6-f8cc9146614c.png)

![Screenshot_20190605-202023](https://user-images.githubusercontent.com/8878532/61740716-4f915880-ad5d-11e9-9857-caeec42338be.png)

### Expected Behavior

Proper padding and overlap for android and smaller devices.

### Actual Behavior

Currently it's not respecting certain other stylings.

<details><summary>Additional Info</summary>

**Comment by vinnyjth** [comment]
@burkeshartsis will review this PR, which might close this.
