### ISSUE TITLE
Apple Pass doesn't generate (spins forever)

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-prototype#954]
### Details

Happened on an iPhone SE on a new user profile. Profile is named Bart Wilson. 

### Expected Behavior

Expected pass to be added to the passbook. 

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by vinnyjth** [comment]
Might have solved this by fixing some certification config errors in heroku.

**Comment by redreceipt** [comment]
this is still broken

**Comment by vinnyjth** [comment]
More details please. Works fine for me in TestFlight

**Comment by redreceipt** [comment]
Sorry, it's seems to be still broken on our app and there's not really any
custom code. I do t have an iPhone so I may others to look for patterns.

--
Michael Neeley
Junior Web Developer
NewSpring Church
www.newspring.cc
Cell: (803) 622-6599

**Comment by vinnyjth** [comment]
Can you slack me your passkit certificates? They should be in your heroku env config

**Comment by vinnyjth** [comment]
Closing issue for now, this is most likely an issue in your heroku config setup.
