### ISSUE TITLE
Devotional list at bottom of devotionals is confusing

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-prototype#958]
### Details

When you are on the first devotional, and navigate to the next devotional, the number and sort changes at the bottom of the devotional. This is due to us removing the current devotional from the list of all devotionals, and using the index of the devotional in the array to determine it's "number" rather than any real logic. 

Open to various solutions for this issue. 

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by richarddubay** [comment]
@vinnyjth FWIW, I believe the current iteration of the NewSpring app does this correctly. It did not remove the current item from the list and it kept the list numbered correctly. Although, and I'm not looking at the code here, I want to say that there was a "# of #" (think: this is devotional 3 of 30) kind of field in EE which we probably don't have in Rock.
