### ISSUE TITLE
Unified Features Block

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#964]
### User Story

As a content creator, I want to be able to define all my features in the same place and in whatever order I want

### Description

This will remove the need for multiple sources of features in Rock and will accept data from one place and disseminate to each feature type

![IMG_20190801_133802](https://user-images.githubusercontent.com/2659478/62315659-cddbb200-b463-11e9-91d5-aa2af8e3fb6c.jpg)

### Why

It's simpler for devs and content creators.

### Acceptance Criteria

* [ ] It should accept data from a `Features` block and resolve to the different types

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by vinnyjth** [comment]
Closed in #966
