### ISSUE TITLE
Add more testing

### ISSUE THREAD

**Issue by richarddubay** [ApollosProject/apollos-prototype#98]
## User Story

As a developer, I want to make sure that our app is tested as well as possible so that I can be confident that what we send to our people works. In this case, implement something like Enzyme (http://airbnb.io/enzyme/docs/guides/react-native.html) to test our components. This would be super helpful for testing events. 

Also, adding some tests to the `<Query>` components would be an excellent addition. See https://dev-blog.apollodata.com/testing-apollos-query-component-d575dc642e04 and https://www.apollographql.com/docs/guides/testing-react-components.html.

#### Problem Details _(Optional)_

* Screenshots, GIFs, or a video
* Any additional information (version, device, etc.)

#### Acceptance Criteria _(Optional)_

I think for a first pass the following would be great:
* [ ] Research whether or not we can use Enzyme (or another equivalent) for testing components.
* [ ] It should implement said library and be able to test components and their events. For instance the `onPressItem` function in `ui/FeedView`. We don't have to cover everything right now ... just get a good base started.
* [ ] It should test our current `<Query>` components.

**Comment by richarddubay** [comment]
@conrad-vanl How do you feel about this? Too much/not enough? I don't know a lot about Enzyme other than "we used to use it on Holtzman" (I never wrote that many tests with it), but I'd be willing to take the lead here and figure it out if you want.

**Comment by conrad-vanl** [comment]
- [ ] break this into two issues (one for enzyme and one for adding test w/ query component)

**Comment by richarddubay** [comment]
This is done with the creation of #109 and #110.
