### ISSUE TITLE
Fix App Store Warnings

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#980]
### User Story

As a partner church, I want my app published :)

### Description

- We need to declare push notifications
- We need to give purposes for needing user locations

![Screenshot_20190806-163453](https://user-images.githubusercontent.com/2659478/62575266-63ae7d00-b868-11e9-8928-d98cac460502.png)

### Why

So the apps can be published to production

### Acceptance Criteria

* [ ] It should not show any warnings from App Store Connect

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by vinnyjth** [comment]
I believe this has been fixed.
