### ISSUE TITLE
Custom Component in Location Finder Crashes

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#984]
### Details

When using a custom component passed into `LocationFinderConnected`, the app crashes.

<img width="989" alt="Screen Shot 2019-08-08 at 4 49 01 PM" src="https://user-images.githubusercontent.com/2659478/62736959-b15bee80-b9fc-11e9-81f7-f83709f73990.png">

### Expected Behavior

Should be able to pass custom component into `LocationFinder`

### Actual Behavior

App crashes.

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by vinnyjth** [comment]
@redreceipt This is confusing, but that prop doesn't accept an already rendered component. It accepts a component function/class that will be rendered. `<Text>` vs `Text`. We have an issue to make sure that any prop named `Component` accepts both.

**Comment by redreceipt** [comment]
This doesn't work either...

<img width="488" alt="Screen Shot 2019-08-11 at 2 25 03 PM" src="https://user-images.githubusercontent.com/2659478/62837963-d9895e80-bc43-11e9-98e5-a2d16057b466.png">

**Comment by redreceipt** [comment]
wait yes it did, there must be another issue I'm having

**Comment by redreceipt** [comment]
I really don't understand why this isn't working. I simply copy and pasted core's location finder to overwrite a portion of it...

<img width="469" alt="Screen Shot 2019-08-11 at 2 45 17 PM" src="https://user-images.githubusercontent.com/2659478/62838181-b9a76a00-bc46-11e9-9d66-33fdc3f785f8.png">
<img width="865" alt="Screen Shot 2019-08-11 at 2 45 33 PM" src="https://user-images.githubusercontent.com/2659478/62838183-bd3af100-bc46-11e9-8f83-18e72a9e9a66.png">
<img width="640" alt="Screen Shot 2019-08-11 at 2 46 30 PM" src="https://user-images.githubusercontent.com/2659478/62838196-d2b01b00-bc46-11e9-9b94-768369d8d5f8.png">

**Comment by redreceipt** [comment]
Ok so when my custom component is wrapped with `<Slide>`, it breaks, works when it's not.

**Comment by redreceipt** [comment]
I'm so confused

**Comment by redreceipt** [comment]
I got it 🤦‍♂
